<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title> 6 Simple and Multiple Regression | Data Applications in Public Administration</title>
  <meta name="description" content="Companion text for PADP 7120" />
  <meta name="generator" content="bookdown 0.20 and GitBook 2.6.7" />

  <meta property="og:title" content=" 6 Simple and Multiple Regression | Data Applications in Public Administration" />
  <meta property="og:type" content="book" />
  <meta property="og:url" content="https://alex-combs.github.io/data-apps-text/" />
  
  <meta property="og:description" content="Companion text for PADP 7120" />
  <meta name="github-repo" content="alex-combs/data-apps-text" />

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content=" 6 Simple and Multiple Regression | Data Applications in Public Administration" />
  
  <meta name="twitter:description" content="Companion text for PADP 7120" />
  

<meta name="author" content="Alex Combs" />



  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="5-data-visualization.html"/>
<link rel="next" href="7-categorical-variables-and-interactions.html"/>
<script src="libs/jquery-2.2.3/jquery.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />









<script src="libs/accessible-code-block-0.0.1/empty-anchor.js"></script>
<script src="libs/htmlwidgets-1.5.1/htmlwidgets.js"></script>
<link href="libs/datatables-css-0.0.0/datatables-crosstalk.css" rel="stylesheet" />
<script src="libs/datatables-binding-0.14/datatables.js"></script>
<link href="libs/dt-core-1.10.20/css/jquery.dataTables.min.css" rel="stylesheet" />
<link href="libs/dt-core-1.10.20/css/jquery.dataTables.extra.css" rel="stylesheet" />
<script src="libs/dt-core-1.10.20/js/jquery.dataTables.min.js"></script>
<link href="libs/crosstalk-1.1.0.1/css/crosstalk.css" rel="stylesheet" />
<script src="libs/crosstalk-1.1.0.1/js/crosstalk.min.js"></script>


<style type="text/css">
code.sourceCode > span { display: inline-block; line-height: 1.25; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode { white-space: pre; position: relative; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
code.sourceCode { white-space: pre-wrap; }
code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">Data Applications in PA</a></li>

<li class="divider"></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i>Preface</a><ul>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#objective"><i class="fa fa-check"></i>Objective</a></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#style-and-structure"><i class="fa fa-check"></i>Style and Structure</a></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#software-requirements"><i class="fa fa-check"></i>Software requirements</a></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#supplemental-resources"><i class="fa fa-check"></i>Supplemental resources</a></li>
</ul></li>
<li class="chapter" data-level="1" data-path="1-intro.html"><a href="1-intro.html"><i class="fa fa-check"></i><b>1</b> Introduction</a><ul>
<li class="chapter" data-level="1.1" data-path="1-intro.html"><a href="1-intro.html#why-statistics"><i class="fa fa-check"></i><b>1.1</b> Why statistics</a></li>
<li class="chapter" data-level="1.2" data-path="1-intro.html"><a href="1-intro.html#professional-standards"><i class="fa fa-check"></i><b>1.2</b> Professional standards</a></li>
<li class="chapter" data-level="1.3" data-path="1-intro.html"><a href="1-intro.html#statistics-in-pa"><i class="fa fa-check"></i><b>1.3</b> Statistics in PA</a></li>
<li class="chapter" data-level="1.4" data-path="1-intro.html"><a href="1-intro.html#using-r"><i class="fa fa-check"></i><b>1.4</b> Using R</a></li>
</ul></li>
<li class="part"><span><b>I Data and Description</b></span></li>
<li class="chapter" data-level="2" data-path="2-data.html"><a href="2-data.html"><i class="fa fa-check"></i><b>2</b> Data</a><ul>
<li class="chapter" data-level="2.1" data-path="2-data.html"><a href="2-data.html#lo2"><i class="fa fa-check"></i><b>2.1</b> Learning objectives</a></li>
<li class="chapter" data-level="2.2" data-path="2-data.html"><a href="2-data.html#rectangular-data"><i class="fa fa-check"></i><b>2.2</b> Rectangular Data</a></li>
<li class="chapter" data-level="2.3" data-path="2-data.html"><a href="2-data.html#types-of-variables"><i class="fa fa-check"></i><b>2.3</b> Types of variables</a><ul>
<li class="chapter" data-level="2.3.1" data-path="2-data.html"><a href="2-data.html#qualitative-variables"><i class="fa fa-check"></i><b>2.3.1</b> Qualitative variables</a></li>
<li class="chapter" data-level="2.3.2" data-path="2-data.html"><a href="2-data.html#quantitative-variables"><i class="fa fa-check"></i><b>2.3.2</b> Quantitative variables</a></li>
<li class="chapter" data-level="2.3.3" data-path="2-data.html"><a href="2-data.html#index-variables"><i class="fa fa-check"></i><b>2.3.3</b> Index variables</a></li>
</ul></li>
<li class="chapter" data-level="2.4" data-path="2-data.html"><a href="2-data.html#dataset-structures"><i class="fa fa-check"></i><b>2.4</b> Dataset structures</a></li>
<li class="chapter" data-level="2.5" data-path="2-data.html"><a href="2-data.html#kt1"><i class="fa fa-check"></i><b>2.5</b> Key terms and concepts</a></li>
</ul></li>
<li class="chapter" data-level="3" data-path="3-measurement-and-missing.html"><a href="3-measurement-and-missing.html"><i class="fa fa-check"></i><b>3</b> Measurement and Missing</a><ul>
<li class="chapter" data-level="3.1" data-path="3-measurement-and-missing.html"><a href="3-measurement-and-missing.html#lo3"><i class="fa fa-check"></i><b>3.1</b> Learning objectives</a></li>
<li class="chapter" data-level="3.2" data-path="3-measurement-and-missing.html"><a href="3-measurement-and-missing.html#credible-analysis"><i class="fa fa-check"></i><b>3.2</b> Credible analysis</a><ul>
<li class="chapter" data-level="3.2.1" data-path="3-measurement-and-missing.html"><a href="3-measurement-and-missing.html#measurement-validity-reliability"><i class="fa fa-check"></i><b>3.2.1</b> Measurement validity &amp; reliability</a></li>
</ul></li>
<li class="chapter" data-level="3.3" data-path="3-measurement-and-missing.html"><a href="3-measurement-and-missing.html#missing-data"><i class="fa fa-check"></i><b>3.3</b> Missing data</a><ul>
<li class="chapter" data-level="3.3.1" data-path="3-measurement-and-missing.html"><a href="3-measurement-and-missing.html#types-of-missing-data"><i class="fa fa-check"></i><b>3.3.1</b> Types of missing data</a></li>
</ul></li>
<li class="chapter" data-level="3.4" data-path="3-measurement-and-missing.html"><a href="3-measurement-and-missing.html#kt2"><i class="fa fa-check"></i><b>3.4</b> Key terms and concepts</a></li>
</ul></li>
<li class="chapter" data-level="4" data-path="4-descriptive-statistics.html"><a href="4-descriptive-statistics.html"><i class="fa fa-check"></i><b>4</b> Descriptive Statistics</a><ul>
<li class="chapter" data-level="4.1" data-path="4-descriptive-statistics.html"><a href="4-descriptive-statistics.html#lo4"><i class="fa fa-check"></i><b>4.1</b> Learning objectives</a></li>
<li class="chapter" data-level="4.2" data-path="4-descriptive-statistics.html"><a href="4-descriptive-statistics.html#two-kinds-of-statistics"><i class="fa fa-check"></i><b>4.2</b> Two kinds of statistics</a></li>
<li class="chapter" data-level="4.3" data-path="4-descriptive-statistics.html"><a href="4-descriptive-statistics.html#distributions"><i class="fa fa-check"></i><b>4.3</b> Distributions</a></li>
<li class="chapter" data-level="4.4" data-path="4-descriptive-statistics.html"><a href="4-descriptive-statistics.html#descriptive-measures"><i class="fa fa-check"></i><b>4.4</b> Descriptive Measures</a><ul>
<li class="chapter" data-level="4.4.1" data-path="4-descriptive-statistics.html"><a href="4-descriptive-statistics.html#measures-of-center"><i class="fa fa-check"></i><b>4.4.1</b> Measures of center</a></li>
<li class="chapter" data-level="4.4.2" data-path="4-descriptive-statistics.html"><a href="4-descriptive-statistics.html#measures-of-spread"><i class="fa fa-check"></i><b>4.4.2</b> Measures of spread</a></li>
<li class="chapter" data-level="4.4.3" data-path="4-descriptive-statistics.html"><a href="4-descriptive-statistics.html#the-normal-distribution"><i class="fa fa-check"></i><b>4.4.3</b> The normal distribution</a></li>
<li class="chapter" data-level="4.4.4" data-path="4-descriptive-statistics.html"><a href="4-descriptive-statistics.html#measures-of-association"><i class="fa fa-check"></i><b>4.4.4</b> Measures of association</a></li>
</ul></li>
<li class="chapter" data-level="4.5" data-path="4-descriptive-statistics.html"><a href="4-descriptive-statistics.html#kt4"><i class="fa fa-check"></i><b>4.5</b> Key terms and concepts</a></li>
</ul></li>
<li class="chapter" data-level="5" data-path="5-data-visualization.html"><a href="5-data-visualization.html"><i class="fa fa-check"></i><b>5</b> Data Visualization</a><ul>
<li class="chapter" data-level="5.1" data-path="5-data-visualization.html"><a href="5-data-visualization.html#lo5"><i class="fa fa-check"></i><b>5.1</b> Learning objectives</a></li>
<li class="chapter" data-level="5.2" data-path="5-data-visualization.html"><a href="5-data-visualization.html#so-many-choices"><i class="fa fa-check"></i><b>5.2</b> So many choices</a></li>
<li class="chapter" data-level="5.3" data-path="5-data-visualization.html"><a href="5-data-visualization.html#distribution"><i class="fa fa-check"></i><b>5.3</b> Distribution</a><ul>
<li class="chapter" data-level="5.3.1" data-path="5-data-visualization.html"><a href="5-data-visualization.html#histogram"><i class="fa fa-check"></i><b>5.3.1</b> Histogram</a></li>
<li class="chapter" data-level="5.3.2" data-path="5-data-visualization.html"><a href="5-data-visualization.html#density"><i class="fa fa-check"></i><b>5.3.2</b> Density</a></li>
<li class="chapter" data-level="5.3.3" data-path="5-data-visualization.html"><a href="5-data-visualization.html#box-plot"><i class="fa fa-check"></i><b>5.3.3</b> Box plot</a></li>
</ul></li>
<li class="chapter" data-level="5.4" data-path="5-data-visualization.html"><a href="5-data-visualization.html#compostion-of-a-category"><i class="fa fa-check"></i><b>5.4</b> Compostion of a category</a><ul>
<li class="chapter" data-level="5.4.1" data-path="5-data-visualization.html"><a href="5-data-visualization.html#pie-charts"><i class="fa fa-check"></i><b>5.4.1</b> Pie charts</a></li>
<li class="chapter" data-level="5.4.2" data-path="5-data-visualization.html"><a href="5-data-visualization.html#bar-chart"><i class="fa fa-check"></i><b>5.4.2</b> Bar chart</a></li>
</ul></li>
<li class="chapter" data-level="5.5" data-path="5-data-visualization.html"><a href="5-data-visualization.html#comparing-between-units"><i class="fa fa-check"></i><b>5.5</b> Comparing between units</a><ul>
<li class="chapter" data-level="5.5.1" data-path="5-data-visualization.html"><a href="5-data-visualization.html#bar-chart-1"><i class="fa fa-check"></i><b>5.5.1</b> Bar chart</a></li>
<li class="chapter" data-level="5.5.2" data-path="5-data-visualization.html"><a href="5-data-visualization.html#dot-plot"><i class="fa fa-check"></i><b>5.5.2</b> Dot plot</a></li>
<li class="chapter" data-level="5.5.3" data-path="5-data-visualization.html"><a href="5-data-visualization.html#line-graph"><i class="fa fa-check"></i><b>5.5.3</b> Line graph</a></li>
</ul></li>
<li class="chapter" data-level="5.6" data-path="5-data-visualization.html"><a href="5-data-visualization.html#association"><i class="fa fa-check"></i><b>5.6</b> Association</a><ul>
<li class="chapter" data-level="5.6.1" data-path="5-data-visualization.html"><a href="5-data-visualization.html#categorical-and-numerical"><i class="fa fa-check"></i><b>5.6.1</b> Categorical and numerical</a></li>
<li class="chapter" data-level="5.6.2" data-path="5-data-visualization.html"><a href="5-data-visualization.html#scatter-plot"><i class="fa fa-check"></i><b>5.6.2</b> Scatter plot</a></li>
</ul></li>
<li class="chapter" data-level="5.7" data-path="5-data-visualization.html"><a href="5-data-visualization.html#kt5"><i class="fa fa-check"></i><b>5.7</b> Key terms and concepts</a></li>
</ul></li>
<li class="part"><span><b>II Regression Models</b></span></li>
<li class="chapter" data-level="6" data-path="6-simple-and-multiple-regression.html"><a href="6-simple-and-multiple-regression.html"><i class="fa fa-check"></i><b>6</b> Simple and Multiple Regression</a><ul>
<li class="chapter" data-level="6.1" data-path="6-simple-and-multiple-regression.html"><a href="6-simple-and-multiple-regression.html#lo6"><i class="fa fa-check"></i><b>6.1</b> Learning objectives</a></li>
<li class="chapter" data-level="6.2" data-path="6-simple-and-multiple-regression.html"><a href="6-simple-and-multiple-regression.html#basic-idea"><i class="fa fa-check"></i><b>6.2</b> Basic idea</a></li>
<li class="chapter" data-level="6.3" data-path="6-simple-and-multiple-regression.html"><a href="6-simple-and-multiple-regression.html#simple-linear-regression"><i class="fa fa-check"></i><b>6.3</b> Simple linear regression</a><ul>
<li class="chapter" data-level="6.3.1" data-path="6-simple-and-multiple-regression.html"><a href="6-simple-and-multiple-regression.html#using-regression"><i class="fa fa-check"></i><b>6.3.1</b> Using regression</a></li>
<li class="chapter" data-level="6.3.2" data-path="6-simple-and-multiple-regression.html"><a href="6-simple-and-multiple-regression.html#the-error-term"><i class="fa fa-check"></i><b>6.3.2</b> The error term</a></li>
<li class="chapter" data-level="6.3.3" data-path="6-simple-and-multiple-regression.html"><a href="6-simple-and-multiple-regression.html#goodness-of-fit"><i class="fa fa-check"></i><b>6.3.3</b> Goodness of fit</a></li>
</ul></li>
<li class="chapter" data-level="6.4" data-path="6-simple-and-multiple-regression.html"><a href="6-simple-and-multiple-regression.html#multiple-regression"><i class="fa fa-check"></i><b>6.4</b> Multiple regression</a><ul>
<li class="chapter" data-level="6.4.1" data-path="6-simple-and-multiple-regression.html"><a href="6-simple-and-multiple-regression.html#using-multiple-regression"><i class="fa fa-check"></i><b>6.4.1</b> Using multiple regression</a></li>
<li class="chapter" data-level="6.4.2" data-path="6-simple-and-multiple-regression.html"><a href="6-simple-and-multiple-regression.html#fit-and-adjusted-r-squared"><i class="fa fa-check"></i><b>6.4.2</b> Fit and adjusted R squared</a></li>
<li class="chapter" data-level="6.4.3" data-path="6-simple-and-multiple-regression.html"><a href="6-simple-and-multiple-regression.html#explanatory-penalty"><i class="fa fa-check"></i><b>6.4.3</b> Explanatory penalty</a></li>
</ul></li>
<li class="chapter" data-level="6.5" data-path="6-simple-and-multiple-regression.html"><a href="6-simple-and-multiple-regression.html#kt6"><i class="fa fa-check"></i><b>6.5</b> Key terms and concepts</a></li>
</ul></li>
<li class="chapter" data-level="7" data-path="7-categorical-variables-and-interactions.html"><a href="7-categorical-variables-and-interactions.html"><i class="fa fa-check"></i><b>7</b> Categorical Variables and Interactions</a><ul>
<li class="chapter" data-level="7.1" data-path="7-categorical-variables-and-interactions.html"><a href="7-categorical-variables-and-interactions.html#lo7"><i class="fa fa-check"></i><b>7.1</b> Learning objectives</a></li>
<li class="chapter" data-level="7.2" data-path="7-categorical-variables-and-interactions.html"><a href="7-categorical-variables-and-interactions.html#parallel-slopes-model"><i class="fa fa-check"></i><b>7.2</b> Parallel slopes model</a><ul>
<li class="chapter" data-level="7.2.1" data-path="7-categorical-variables-and-interactions.html"><a href="7-categorical-variables-and-interactions.html#using-parallel-slopes"><i class="fa fa-check"></i><b>7.2.1</b> Using parallel slopes</a></li>
<li class="chapter" data-level="7.2.2" data-path="7-categorical-variables-and-interactions.html"><a href="7-categorical-variables-and-interactions.html#variations"><i class="fa fa-check"></i><b>7.2.2</b> Variations</a></li>
</ul></li>
<li class="chapter" data-level="7.3" data-path="7-categorical-variables-and-interactions.html"><a href="7-categorical-variables-and-interactions.html#interaction-model"><i class="fa fa-check"></i><b>7.3</b> Interaction model</a><ul>
<li class="chapter" data-level="7.3.1" data-path="7-categorical-variables-and-interactions.html"><a href="7-categorical-variables-and-interactions.html#using-an-interaction"><i class="fa fa-check"></i><b>7.3.1</b> Using an interaction</a></li>
<li class="chapter" data-level="7.3.2" data-path="7-categorical-variables-and-interactions.html"><a href="7-categorical-variables-and-interactions.html#variations-1"><i class="fa fa-check"></i><b>7.3.2</b> Variations</a></li>
</ul></li>
<li class="chapter" data-level="7.4" data-path="7-categorical-variables-and-interactions.html"><a href="7-categorical-variables-and-interactions.html#linear-probability-model"><i class="fa fa-check"></i><b>7.4</b> Linear probability model</a><ul>
<li class="chapter" data-level="7.4.1" data-path="7-categorical-variables-and-interactions.html"><a href="7-categorical-variables-and-interactions.html#using-lpm"><i class="fa fa-check"></i><b>7.4.1</b> Using LPM</a></li>
<li class="chapter" data-level="7.4.2" data-path="7-categorical-variables-and-interactions.html"><a href="7-categorical-variables-and-interactions.html#fit"><i class="fa fa-check"></i><b>7.4.2</b> Fit</a></li>
</ul></li>
<li class="chapter" data-level="7.5" data-path="7-categorical-variables-and-interactions.html"><a href="7-categorical-variables-and-interactions.html#kt7"><i class="fa fa-check"></i><b>7.5</b> Key terms and concepts</a></li>
</ul></li>
<li class="chapter" data-level="8" data-path="8-nonlinear-variables.html"><a href="8-nonlinear-variables.html"><i class="fa fa-check"></i><b>8</b> Nonlinear Variables</a><ul>
<li class="chapter" data-level="8.1" data-path="8-nonlinear-variables.html"><a href="8-nonlinear-variables.html#lo8"><i class="fa fa-check"></i><b>8.1</b> Learning objectives</a></li>
<li class="chapter" data-level="8.2" data-path="8-nonlinear-variables.html"><a href="8-nonlinear-variables.html#quadratic"><i class="fa fa-check"></i><b>8.2</b> Quadratic</a><ul>
<li class="chapter" data-level="8.2.1" data-path="8-nonlinear-variables.html"><a href="8-nonlinear-variables.html#using-quadratics"><i class="fa fa-check"></i><b>8.2.1</b> Using quadratics</a></li>
</ul></li>
<li class="chapter" data-level="8.3" data-path="8-nonlinear-variables.html"><a href="8-nonlinear-variables.html#log-models"><i class="fa fa-check"></i><b>8.3</b> Log models</a><ul>
<li class="chapter" data-level="8.3.1" data-path="8-nonlinear-variables.html"><a href="8-nonlinear-variables.html#logarithmic-scales"><i class="fa fa-check"></i><b>8.3.1</b> Logarithmic scales</a></li>
<li class="chapter" data-level="8.3.2" data-path="8-nonlinear-variables.html"><a href="8-nonlinear-variables.html#percent-v-percentage-point-change"><i class="fa fa-check"></i><b>8.3.2</b> Percent v percentage point change</a></li>
<li class="chapter" data-level="8.3.3" data-path="8-nonlinear-variables.html"><a href="8-nonlinear-variables.html#why-logs-in-regression"><i class="fa fa-check"></i><b>8.3.3</b> Why logs in regression</a></li>
<li class="chapter" data-level="8.3.4" data-path="8-nonlinear-variables.html"><a href="8-nonlinear-variables.html#using-log-models"><i class="fa fa-check"></i><b>8.3.4</b> Using log models</a></li>
</ul></li>
<li class="chapter" data-level="8.4" data-path="8-nonlinear-variables.html"><a href="8-nonlinear-variables.html#kt8"><i class="fa fa-check"></i><b>8.4</b> Key terms and concepts</a></li>
</ul></li>
<li class="chapter" data-level="9" data-path="9-causation-and-bias.html"><a href="9-causation-and-bias.html"><i class="fa fa-check"></i><b>9</b> Causation and Bias</a><ul>
<li class="chapter" data-level="9.1" data-path="9-causation-and-bias.html"><a href="9-causation-and-bias.html#lo9"><i class="fa fa-check"></i><b>9.1</b> Learning objectives</a></li>
<li class="chapter" data-level="9.2" data-path="9-causation-and-bias.html"><a href="9-causation-and-bias.html#causality"><i class="fa fa-check"></i><b>9.2</b> Causality</a></li>
<li class="chapter" data-level="9.3" data-path="9-causation-and-bias.html"><a href="9-causation-and-bias.html#directed-acyclical-graphs"><i class="fa fa-check"></i><b>9.3</b> Directed acyclical graphs</a><ul>
<li class="chapter" data-level="9.3.1" data-path="9-causation-and-bias.html"><a href="9-causation-and-bias.html#evaluationg-dags"><i class="fa fa-check"></i><b>9.3.1</b> Evaluationg DAGs</a></li>
<li class="chapter" data-level="9.3.2" data-path="9-causation-and-bias.html"><a href="9-causation-and-bias.html#backdoor-criterion"><i class="fa fa-check"></i><b>9.3.2</b> Backdoor criterion</a></li>
<li class="chapter" data-level="9.3.3" data-path="9-causation-and-bias.html"><a href="9-causation-and-bias.html#dags-and-regression"><i class="fa fa-check"></i><b>9.3.3</b> DAGs and regression</a></li>
</ul></li>
<li class="chapter" data-level="9.4" data-path="9-causation-and-bias.html"><a href="9-causation-and-bias.html#direction-of-ovb"><i class="fa fa-check"></i><b>9.4</b> Direction of OVB</a></li>
<li class="chapter" data-level="9.5" data-path="9-causation-and-bias.html"><a href="9-causation-and-bias.html#usefulness"><i class="fa fa-check"></i><b>9.5</b> Usefulness</a></li>
<li class="chapter" data-level="9.6" data-path="9-causation-and-bias.html"><a href="9-causation-and-bias.html#kt9"><i class="fa fa-check"></i><b>9.6</b> Key terms and concepts</a></li>
</ul></li>
<li class="part"><span><b>III Inference</b></span></li>
<li class="chapter" data-level="10" data-path="10-sampling.html"><a href="10-sampling.html"><i class="fa fa-check"></i><b>10</b> Sampling</a><ul>
<li class="chapter" data-level="10.1" data-path="10-sampling.html"><a href="10-sampling.html#lo10"><i class="fa fa-check"></i><b>10.1</b> Learning objectives</a></li>
<li class="chapter" data-level="10.2" data-path="10-sampling.html"><a href="10-sampling.html#normal-distribution"><i class="fa fa-check"></i><b>10.2</b> Normal distribution</a></li>
<li class="chapter" data-level="10.3" data-path="10-sampling.html"><a href="10-sampling.html#sampling-distribution"><i class="fa fa-check"></i><b>10.3</b> Sampling Distribution</a></li>
<li class="chapter" data-level="10.4" data-path="10-sampling.html"><a href="10-sampling.html#central-limit-theorem"><i class="fa fa-check"></i><b>10.4</b> Central Limit Theorem</a></li>
<li class="chapter" data-level="10.5" data-path="10-sampling.html"><a href="10-sampling.html#confidence-intervals"><i class="fa fa-check"></i><b>10.5</b> Confidence intervals</a></li>
<li class="chapter" data-level="10.6" data-path="10-sampling.html"><a href="10-sampling.html#conclusion"><i class="fa fa-check"></i><b>10.6</b> Conclusion</a></li>
<li class="chapter" data-level="10.7" data-path="10-sampling.html"><a href="10-sampling.html#kt10"><i class="fa fa-check"></i><b>10.7</b> Key terms and concepts</a></li>
</ul></li>
<li class="chapter" data-level="11" data-path="11-surveys-and-evaluations.html"><a href="11-surveys-and-evaluations.html"><i class="fa fa-check"></i><b>11</b> Surveys and Evaluations</a><ul>
<li class="chapter" data-level="11.1" data-path="11-surveys-and-evaluations.html"><a href="11-surveys-and-evaluations.html#lo11"><i class="fa fa-check"></i><b>11.1</b> Learning objectives</a></li>
<li class="chapter" data-level="11.2" data-path="11-surveys-and-evaluations.html"><a href="11-surveys-and-evaluations.html#sample-size"><i class="fa fa-check"></i><b>11.2</b> Sample size</a></li>
<li class="chapter" data-level="11.3" data-path="11-surveys-and-evaluations.html"><a href="11-surveys-and-evaluations.html#survey-weights"><i class="fa fa-check"></i><b>11.3</b> Survey weights</a></li>
<li class="chapter" data-level="11.4" data-path="11-surveys-and-evaluations.html"><a href="11-surveys-and-evaluations.html#hypothesis-testing"><i class="fa fa-check"></i><b>11.4</b> Hypothesis testing</a><ul>
<li class="chapter" data-level="11.4.1" data-path="11-surveys-and-evaluations.html"><a href="11-surveys-and-evaluations.html#null-and-alternative-hypos"><i class="fa fa-check"></i><b>11.4.1</b> Null and alternative hypos</a></li>
<li class="chapter" data-level="11.4.2" data-path="11-surveys-and-evaluations.html"><a href="11-surveys-and-evaluations.html#conclusion-and-error-type"><i class="fa fa-check"></i><b>11.4.2</b> Conclusion and error type</a></li>
<li class="chapter" data-level="11.4.3" data-path="11-surveys-and-evaluations.html"><a href="11-surveys-and-evaluations.html#decision-rule"><i class="fa fa-check"></i><b>11.4.3</b> Decision rule</a></li>
</ul></li>
<li class="chapter" data-level="11.5" data-path="11-surveys-and-evaluations.html"><a href="11-surveys-and-evaluations.html#chi-square-test"><i class="fa fa-check"></i><b>11.5</b> Chi-square test</a></li>
<li class="chapter" data-level="11.6" data-path="11-surveys-and-evaluations.html"><a href="11-surveys-and-evaluations.html#t-test"><i class="fa fa-check"></i><b>11.6</b> T-test</a></li>
<li class="chapter" data-level="11.7" data-path="11-surveys-and-evaluations.html"><a href="11-surveys-and-evaluations.html#kt11"><i class="fa fa-check"></i><b>11.7</b> Key terms and concepts</a></li>
</ul></li>
<li class="chapter" data-level="12" data-path="12-regression-inference.html"><a href="12-regression-inference.html"><i class="fa fa-check"></i><b>12</b> Regression Inference</a><ul>
<li class="chapter" data-level="12.1" data-path="12-regression-inference.html"><a href="12-regression-inference.html#lo12"><i class="fa fa-check"></i><b>12.1</b> Learning objectives</a></li>
<li class="chapter" data-level="12.2" data-path="12-regression-inference.html"><a href="12-regression-inference.html#regression-table"><i class="fa fa-check"></i><b>12.2</b> Regression table</a></li>
<li class="chapter" data-level="12.3" data-path="12-regression-inference.html"><a href="12-regression-inference.html#other-hypotheses"><i class="fa fa-check"></i><b>12.3</b> Other hypotheses</a></li>
<li class="chapter" data-level="12.4" data-path="12-regression-inference.html"><a href="12-regression-inference.html#practical-significance"><i class="fa fa-check"></i><b>12.4</b> Practical significance</a></li>
</ul></li>
<li class="chapter" data-level="13" data-path="13-kt12.html"><a href="13-kt12.html"><i class="fa fa-check"></i><b>13</b> Key terms and concepts</a></li>
<li class="chapter" data-level="14" data-path="14-regression-diagnostics.html"><a href="14-regression-diagnostics.html"><i class="fa fa-check"></i><b>14</b> Regression Diagnostics</a><ul>
<li class="chapter" data-level="14.1" data-path="14-regression-diagnostics.html"><a href="14-regression-diagnostics.html#lo13"><i class="fa fa-check"></i><b>14.1</b> Learning objectives</a></li>
<li class="chapter" data-level="14.2" data-path="14-regression-diagnostics.html"><a href="14-regression-diagnostics.html#classical-assumptions"><i class="fa fa-check"></i><b>14.2</b> Classical assumptions</a></li>
<li class="chapter" data-level="14.3" data-path="14-regression-diagnostics.html"><a href="14-regression-diagnostics.html#multicollinearity"><i class="fa fa-check"></i><b>14.3</b> Multicollinearity</a></li>
<li class="chapter" data-level="14.4" data-path="14-regression-diagnostics.html"><a href="14-regression-diagnostics.html#influential-data"><i class="fa fa-check"></i><b>14.4</b> Influential Data</a></li>
<li class="chapter" data-level="14.5" data-path="14-regression-diagnostics.html"><a href="14-regression-diagnostics.html#kt13"><i class="fa fa-check"></i><b>14.5</b> Key terms and concepts</a></li>
</ul></li>
<li class="part"><span><b>IV Advanced Topics</b></span></li>
<li class="chapter" data-level="15" data-path="15-forecasting.html"><a href="15-forecasting.html"><i class="fa fa-check"></i><b>15</b> Forecasting</a><ul>
<li class="chapter" data-level="15.1" data-path="15-forecasting.html"><a href="15-forecasting.html#what-is-forecasting"><i class="fa fa-check"></i><b>15.1</b> What is forecasting</a></li>
<li class="chapter" data-level="15.2" data-path="15-forecasting.html"><a href="15-forecasting.html#patterns"><i class="fa fa-check"></i><b>15.2</b> Patterns</a><ul>
<li class="chapter" data-level="15.2.1" data-path="15-forecasting.html"><a href="15-forecasting.html#autocorrelation"><i class="fa fa-check"></i><b>15.2.1</b> Autocorrelation</a></li>
</ul></li>
<li class="chapter" data-level="15.3" data-path="15-forecasting.html"><a href="15-forecasting.html#forecasting-basics"><i class="fa fa-check"></i><b>15.3</b> Forecasting basics</a><ul>
<li class="chapter" data-level="15.3.1" data-path="15-forecasting.html"><a href="15-forecasting.html#evaluation"><i class="fa fa-check"></i><b>15.3.1</b> Evaluation</a></li>
<li class="chapter" data-level="15.3.2" data-path="15-forecasting.html"><a href="15-forecasting.html#models"><i class="fa fa-check"></i><b>15.3.2</b> Models</a></li>
</ul></li>
<li class="chapter" data-level="15.4" data-path="15-forecasting.html"><a href="15-forecasting.html#recap"><i class="fa fa-check"></i><b>15.4</b> Recap</a></li>
</ul></li>
<li class="chapter" data-level="16" data-path="16-panel-analysis.html"><a href="16-panel-analysis.html"><i class="fa fa-check"></i><b>16</b> Panel Analysis</a><ul>
<li class="chapter" data-level="16.1" data-path="16-panel-analysis.html"><a href="16-panel-analysis.html#panel-data"><i class="fa fa-check"></i><b>16.1</b> Panel data</a></li>
<li class="chapter" data-level="16.2" data-path="16-panel-analysis.html"><a href="16-panel-analysis.html#fixed-effects"><i class="fa fa-check"></i><b>16.2</b> Fixed effects</a></li>
</ul></li>
<li class="part"><span><b>V R Chapters</b></span></li>
<li class="chapter" data-level="17" data-path="17-r-introduction.html"><a href="17-r-introduction.html"><i class="fa fa-check"></i><b>17</b> R Introduction</a><ul>
<li class="chapter" data-level="17.1" data-path="17-r-introduction.html"><a href="17-r-introduction.html#r-chapter-structure"><i class="fa fa-check"></i><b>17.1</b> R chapter structure</a></li>
<li class="chapter" data-level="17.2" data-path="17-r-introduction.html"><a href="17-r-introduction.html#r-chapter-feedback"><i class="fa fa-check"></i><b>17.2</b> R chapter feedback</a></li>
<li class="chapter" data-level="17.3" data-path="17-r-introduction.html"><a href="17-r-introduction.html#what-is-r-and-rstudio"><i class="fa fa-check"></i><b>17.3</b> What is R and RStudio</a></li>
<li class="chapter" data-level="17.4" data-path="17-r-introduction.html"><a href="17-r-introduction.html#installing-r-and-rstudio"><i class="fa fa-check"></i><b>17.4</b> Installing R and RStudio</a></li>
<li class="chapter" data-level="17.5" data-path="17-r-introduction.html"><a href="17-r-introduction.html#rstudio-orientation"><i class="fa fa-check"></i><b>17.5</b> RStudio orientation</a><ul>
<li class="chapter" data-level="17.5.1" data-path="17-r-introduction.html"><a href="17-r-introduction.html#r-packages"><i class="fa fa-check"></i><b>17.5.1</b> R Packages</a></li>
</ul></li>
<li class="chapter" data-level="17.6" data-path="17-r-introduction.html"><a href="17-r-introduction.html#submit"><i class="fa fa-check"></i><b>17.6</b> Submit</a></li>
<li class="chapter" data-level="17.7" data-path="17-r-introduction.html"><a href="17-r-introduction.html#additional-resources"><i class="fa fa-check"></i><b>17.7</b> Additional Resources</a></li>
</ul></li>
<li class="chapter" data-level="18" data-path="18-r-data.html"><a href="18-r-data.html"><i class="fa fa-check"></i><b>18</b> R Data</a><ul>
<li class="chapter" data-level="18.1" data-path="18-r-data.html"><a href="18-r-data.html#learning-objectives"><i class="fa fa-check"></i><b>18.1</b> Learning Objectives</a></li>
<li class="chapter" data-level="18.2" data-path="18-r-data.html"><a href="18-r-data.html#set-up"><i class="fa fa-check"></i><b>18.2</b> Set-up</a></li>
<li class="chapter" data-level="18.3" data-path="18-r-data.html"><a href="18-r-data.html#viewing-datasets"><i class="fa fa-check"></i><b>18.3</b> Viewing datasets</a><ul>
<li class="chapter" data-level="18.3.1" data-path="18-r-data.html"><a href="18-r-data.html#warning-about-view"><i class="fa fa-check"></i><b>18.3.1</b> Warning about View</a></li>
</ul></li>
<li class="chapter" data-level="18.4" data-path="18-r-data.html"><a href="18-r-data.html#glimpsing-datasets"><i class="fa fa-check"></i><b>18.4</b> Glimpsing Datasets</a></li>
<li class="chapter" data-level="18.5" data-path="18-r-data.html"><a href="18-r-data.html#preview-first-or-last-few-rows"><i class="fa fa-check"></i><b>18.5</b> Preview first or last few rows</a></li>
<li class="chapter" data-level="18.6" data-path="17-r-introduction.html"><a href="17-r-introduction.html#submit"><i class="fa fa-check"></i><b>18.6</b> Submit</a></li>
</ul></li>
<li class="chapter" data-level="19" data-path="19-r-missing-data.html"><a href="19-r-missing-data.html"><i class="fa fa-check"></i><b>19</b> R Missing Data</a><ul>
<li class="chapter" data-level="19.1" data-path="18-r-data.html"><a href="18-r-data.html#learning-objectives"><i class="fa fa-check"></i><b>19.1</b> Learning Objectives</a></li>
<li class="chapter" data-level="19.2" data-path="18-r-data.html"><a href="18-r-data.html#set-up"><i class="fa fa-check"></i><b>19.2</b> Set-up</a></li>
<li class="chapter" data-level="19.3" data-path="2-data.html"><a href="2-data.html#data"><i class="fa fa-check"></i><b>19.3</b> Data</a></li>
<li class="chapter" data-level="19.4" data-path="19-r-missing-data.html"><a href="19-r-missing-data.html#checking-for-missing-data"><i class="fa fa-check"></i><b>19.4</b> Checking for missing data</a></li>
<li class="chapter" data-level="19.5" data-path="19-r-missing-data.html"><a href="19-r-missing-data.html#counting-missing-values"><i class="fa fa-check"></i><b>19.5</b> Counting missing values</a></li>
<li class="chapter" data-level="19.6" data-path="19-r-missing-data.html"><a href="19-r-missing-data.html#bypassing-missing-values"><i class="fa fa-check"></i><b>19.6</b> Bypassing missing values</a></li>
<li class="chapter" data-level="19.7" data-path="19-r-missing-data.html"><a href="19-r-missing-data.html#replacing-missing-values"><i class="fa fa-check"></i><b>19.7</b> Replacing missing values</a></li>
<li class="chapter" data-level="19.8" data-path="17-r-introduction.html"><a href="17-r-introduction.html#submit"><i class="fa fa-check"></i><b>19.8</b> Submit</a></li>
</ul></li>
<li class="chapter" data-level="20" data-path="20-r-description.html"><a href="20-r-description.html"><i class="fa fa-check"></i><b>20</b> R Description</a><ul>
<li class="chapter" data-level="20.1" data-path="18-r-data.html"><a href="18-r-data.html#learning-objectives"><i class="fa fa-check"></i><b>20.1</b> Learning Objectives</a></li>
<li class="chapter" data-level="20.2" data-path="18-r-data.html"><a href="18-r-data.html#set-up"><i class="fa fa-check"></i><b>20.2</b> Set-up</a></li>
<li class="chapter" data-level="20.3" data-path="20-r-description.html"><a href="20-r-description.html#introduction"><i class="fa fa-check"></i><b>20.3</b> Introduction</a></li>
<li class="chapter" data-level="20.4" data-path="20-r-description.html"><a href="20-r-description.html#summary-table"><i class="fa fa-check"></i><b>20.4</b> Summary Table</a></li>
<li class="chapter" data-level="20.5" data-path="20-r-description.html"><a href="20-r-description.html#using-arsenal"><i class="fa fa-check"></i><b>20.5</b> Using Arsenal</a><ul>
<li class="chapter" data-level="20.5.1" data-path="20-r-description.html"><a href="20-r-description.html#adjustments"><i class="fa fa-check"></i><b>20.5.1</b> Adjustments</a></li>
<li class="chapter" data-level="20.5.2" data-path="20-r-description.html"><a href="20-r-description.html#export-to-csv"><i class="fa fa-check"></i><b>20.5.2</b> Export to CSV</a></li>
</ul></li>
<li class="chapter" data-level="20.6" data-path="17-r-introduction.html"><a href="17-r-introduction.html#submit"><i class="fa fa-check"></i><b>20.6</b> Submit</a></li>
</ul></li>
<li class="chapter" data-level="21" data-path="21-r-visualization.html"><a href="21-r-visualization.html"><i class="fa fa-check"></i><b>21</b> R Visualization</a><ul>
<li class="chapter" data-level="21.1" data-path="18-r-data.html"><a href="18-r-data.html#learning-objectives"><i class="fa fa-check"></i><b>21.1</b> Learning Objectives</a></li>
<li class="chapter" data-level="21.2" data-path="18-r-data.html"><a href="18-r-data.html#set-up"><i class="fa fa-check"></i><b>21.2</b> Set-up</a></li>
<li class="chapter" data-level="21.3" data-path="21-r-visualization.html"><a href="21-r-visualization.html#grammar-of-graphics"><i class="fa fa-check"></i><b>21.3</b> Grammar of graphics</a></li>
<li class="chapter" data-level="21.4" data-path="5-data-visualization.html"><a href="5-data-visualization.html#histogram"><i class="fa fa-check"></i><b>21.4</b> Histogram</a></li>
<li class="chapter" data-level="21.5" data-path="5-data-visualization.html"><a href="5-data-visualization.html#box-plot"><i class="fa fa-check"></i><b>21.5</b> Box plot</a></li>
<li class="chapter" data-level="21.6" data-path="5-data-visualization.html"><a href="5-data-visualization.html#bar-chart"><i class="fa fa-check"></i><b>21.6</b> Bar chart</a></li>
<li class="chapter" data-level="21.7" data-path="5-data-visualization.html"><a href="5-data-visualization.html#scatter-plot"><i class="fa fa-check"></i><b>21.7</b> Scatter plot</a></li>
<li class="chapter" data-level="21.8" data-path="5-data-visualization.html"><a href="5-data-visualization.html#line-graph"><i class="fa fa-check"></i><b>21.8</b> Line graph</a></li>
<li class="chapter" data-level="21.9" data-path="17-r-introduction.html"><a href="17-r-introduction.html#submit"><i class="fa fa-check"></i><b>21.9</b> Submit</a></li>
</ul></li>
<li class="chapter" data-level="22" data-path="22-r-regression.html"><a href="22-r-regression.html"><i class="fa fa-check"></i><b>22</b> R Regression</a><ul>
<li class="chapter" data-level="22.1" data-path="18-r-data.html"><a href="18-r-data.html#learning-objectives"><i class="fa fa-check"></i><b>22.1</b> Learning Objectives</a></li>
<li class="chapter" data-level="22.2" data-path="18-r-data.html"><a href="18-r-data.html#set-up"><i class="fa fa-check"></i><b>22.2</b> Set-up</a></li>
<li class="chapter" data-level="22.3" data-path="22-r-regression.html"><a href="22-r-regression.html#running-regression"><i class="fa fa-check"></i><b>22.3</b> Running Regression</a></li>
<li class="chapter" data-level="22.4" data-path="22-r-regression.html"><a href="22-r-regression.html#reporting-results"><i class="fa fa-check"></i><b>22.4</b> Reporting Results</a><ul>
<li class="chapter" data-level="22.4.1" data-path="22-r-regression.html"><a href="22-r-regression.html#moderndive"><i class="fa fa-check"></i><b>22.4.1</b> Moderndive</a></li>
<li class="chapter" data-level="22.4.2" data-path="22-r-regression.html"><a href="22-r-regression.html#base-r"><i class="fa fa-check"></i><b>22.4.2</b> Base R</a></li>
</ul></li>
<li class="chapter" data-level="22.5" data-path="17-r-introduction.html"><a href="17-r-introduction.html#submit"><i class="fa fa-check"></i><b>22.5</b> Submit</a></li>
</ul></li>
<li class="chapter" data-level="23" data-path="23-r-interactions.html"><a href="23-r-interactions.html"><i class="fa fa-check"></i><b>23</b> R Interactions</a><ul>
<li class="chapter" data-level="23.1" data-path="18-r-data.html"><a href="18-r-data.html#learning-objectives"><i class="fa fa-check"></i><b>23.1</b> Learning Objectives</a></li>
<li class="chapter" data-level="23.2" data-path="18-r-data.html"><a href="18-r-data.html#set-up"><i class="fa fa-check"></i><b>23.2</b> Set-up</a></li>
<li class="chapter" data-level="23.3" data-path="23-r-interactions.html"><a href="23-r-interactions.html#including-an-interaction"><i class="fa fa-check"></i><b>23.3</b> Including an interaction</a></li>
<li class="chapter" data-level="23.4" data-path="17-r-introduction.html"><a href="17-r-introduction.html#submit"><i class="fa fa-check"></i><b>23.4</b> Submit</a></li>
</ul></li>
<li class="chapter" data-level="24" data-path="24-r-nonlinear-regression.html"><a href="24-r-nonlinear-regression.html"><i class="fa fa-check"></i><b>24</b> R Nonlinear Regression</a><ul>
<li class="chapter" data-level="24.1" data-path="18-r-data.html"><a href="18-r-data.html#learning-objectives"><i class="fa fa-check"></i><b>24.1</b> Learning Objectives</a></li>
<li class="chapter" data-level="24.2" data-path="18-r-data.html"><a href="18-r-data.html#set-up"><i class="fa fa-check"></i><b>24.2</b> Set-up</a></li>
<li class="chapter" data-level="24.3" data-path="24-r-nonlinear-regression.html"><a href="24-r-nonlinear-regression.html#quadratic-term"><i class="fa fa-check"></i><b>24.3</b> Quadratic term</a></li>
<li class="chapter" data-level="24.4" data-path="24-r-nonlinear-regression.html"><a href="24-r-nonlinear-regression.html#log-transformation"><i class="fa fa-check"></i><b>24.4</b> Log Transformation</a></li>
<li class="chapter" data-level="24.5" data-path="17-r-introduction.html"><a href="17-r-introduction.html#submit"><i class="fa fa-check"></i><b>24.5</b> Submit</a></li>
</ul></li>
<li class="chapter" data-level="25" data-path="25-r-evaluations.html"><a href="25-r-evaluations.html"><i class="fa fa-check"></i><b>25</b> R Evaluations</a><ul>
<li class="chapter" data-level="25.1" data-path="25-r-evaluations.html"><a href="25-r-evaluations.html#learning-outcomes"><i class="fa fa-check"></i><b>25.1</b> Learning Outcomes</a></li>
<li class="chapter" data-level="25.2" data-path="18-r-data.html"><a href="18-r-data.html#set-up"><i class="fa fa-check"></i><b>25.2</b> Set-up</a></li>
<li class="chapter" data-level="25.3" data-path="11-surveys-and-evaluations.html"><a href="11-surveys-and-evaluations.html#chi-square-test"><i class="fa fa-check"></i><b>25.3</b> Chi-square test</a><ul>
<li class="chapter" data-level="25.3.1" data-path="25-r-evaluations.html"><a href="25-r-evaluations.html#cross-tab"><i class="fa fa-check"></i><b>25.3.1</b> Cross-tab</a></li>
<li class="chapter" data-level="25.3.2" data-path="25-r-evaluations.html"><a href="25-r-evaluations.html#run-chi-square"><i class="fa fa-check"></i><b>25.3.2</b> Run chi-square</a></li>
</ul></li>
<li class="chapter" data-level="25.4" data-path="25-r-evaluations.html"><a href="25-r-evaluations.html#t-tests"><i class="fa fa-check"></i><b>25.4</b> T-tests</a><ul>
<li class="chapter" data-level="25.4.1" data-path="25-r-evaluations.html"><a href="25-r-evaluations.html#independent-t-test"><i class="fa fa-check"></i><b>25.4.1</b> Independent t-test</a></li>
<li class="chapter" data-level="25.4.2" data-path="25-r-evaluations.html"><a href="25-r-evaluations.html#dependent-t-test"><i class="fa fa-check"></i><b>25.4.2</b> Dependent t-test</a></li>
</ul></li>
<li class="chapter" data-level="25.5" data-path="17-r-introduction.html"><a href="17-r-introduction.html#submit"><i class="fa fa-check"></i><b>25.5</b> Submit</a></li>
</ul></li>
<li class="chapter" data-level="26" data-path="26-r-regression-diagnostics.html"><a href="26-r-regression-diagnostics.html"><i class="fa fa-check"></i><b>26</b> R Regression Diagnostics</a><ul>
<li class="chapter" data-level="26.1" data-path="25-r-evaluations.html"><a href="25-r-evaluations.html#learning-outcomes"><i class="fa fa-check"></i><b>26.1</b> Learning Outcomes</a></li>
<li class="chapter" data-level="26.2" data-path="18-r-data.html"><a href="18-r-data.html#set-up"><i class="fa fa-check"></i><b>26.2</b> Set-up</a></li>
<li class="chapter" data-level="26.3" data-path="26-r-regression-diagnostics.html"><a href="26-r-regression-diagnostics.html#rvf-and-rvl"><i class="fa fa-check"></i><b>26.3</b> RVF and RVL</a></li>
<li class="chapter" data-level="26.4" data-path="26-r-regression-diagnostics.html"><a href="26-r-regression-diagnostics.html#vif"><i class="fa fa-check"></i><b>26.4</b> VIF</a></li>
<li class="chapter" data-level="26.5" data-path="26-r-regression-diagnostics.html"><a href="26-r-regression-diagnostics.html#exclude-observations"><i class="fa fa-check"></i><b>26.5</b> Exclude observations</a></li>
<li class="chapter" data-level="26.6" data-path="17-r-introduction.html"><a href="17-r-introduction.html#submit"><i class="fa fa-check"></i><b>26.6</b> Submit</a></li>
</ul></li>
<li class="appendix"><span><b>Appendix</b></span></li>
<li class="chapter" data-level="A" data-path="A-wrangle-and-tidy-reference.html"><a href="A-wrangle-and-tidy-reference.html"><i class="fa fa-check"></i><b>A</b> Wrangle and Tidy Reference</a><ul>
<li class="chapter" data-level="A.1" data-path="A-wrangle-and-tidy-reference.html"><a href="A-wrangle-and-tidy-reference.html#cheatsheets"><i class="fa fa-check"></i><b>A.1</b> Cheatsheets</a></li>
<li class="chapter" data-level="A.2" data-path="A-wrangle-and-tidy-reference.html"><a href="A-wrangle-and-tidy-reference.html#common-functions"><i class="fa fa-check"></i><b>A.2</b> Common functions</a><ul>
<li class="chapter" data-level="A.2.1" data-path="A-wrangle-and-tidy-reference.html"><a href="A-wrangle-and-tidy-reference.html#wrangle-verbs"><i class="fa fa-check"></i><b>A.2.1</b> Wrangle Verbs</a></li>
<li class="chapter" data-level="A.2.2" data-path="A-wrangle-and-tidy-reference.html"><a href="A-wrangle-and-tidy-reference.html#tidy-verbs"><i class="fa fa-check"></i><b>A.2.2</b> Tidy Verbs</a></li>
</ul></li>
</ul></li>
<li class="divider"></li>
<li><a href="https://github.com/rstudio/bookdown" target="blank">Published with bookdown</a></li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Data Applications in Public Administration</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="simple-and-multiple-regression" class="section level1">
<h1><span class="header-section-number"> 6</span> Simple and Multiple Regression</h1>
<blockquote>
<p><em>“You can lead a horse to water but you can’t make him enter regional distribution codes in data field 97 to facilitate regression analysis on the back end.”</em></p>
<p>—John Cleese</p>
</blockquote>
<div id="lo6" class="section level2">
<h2><span class="header-section-number">6.1</span> Learning objectives</h2>
<div class="learncheck">
<ul>
<li>
Identify and explain the components of a population or sample regression model
</li>
<li>
Explain the difference between a deterministic equation of a line and a statistical, probabilistic equation of a line
</li>
<li>
Given regression results, provide the predicted change in the outcome given a change in the explanatory variable(s)
</li>
<li>
Given regression results, provide the predicted value of the outcome given a value of the explanatory variable(s)
</li>
<li>
Explain what the error term in a regression model represents
</li>
<li>
Interpret measures of fit in a regression model and explain their relative strengths and weaknesses
</li>
</ul>
</div>
</div>
<div id="basic-idea" class="section level2">
<h2><span class="header-section-number">6.2</span> Basic idea</h2>
<p>The basic idea of regression is really quite simple. Regression calculates a line through a scatter plot of two variables so that we can summarize how much our variable on the y axis changes given a change in the variable on our x variable. Or, we can use a given value for our x variable to predict a value for our y variable. That’s all it is–a line drawn to represent the association between two variables.</p>
<p>We all learned the equation for a line back in middle school, which probably looked something like the following:</p>
<p><span class="math display" id="eq:line">\[\begin{equation}
y = mx + b
\tag{6.1}
\end{equation}\]</span></p>
<p>where <span class="math inline">\(m\)</span> is the slope of the line and <span class="math inline">\(b\)</span> is the y-intercept. If we know the slope and intercept for a line, then, given a value for <span class="math inline">\(x\)</span>, we can compute <span class="math inline">\(y\)</span>. Given a change in <span class="math inline">\(x\)</span>, we can compute a change in <span class="math inline">\(y\)</span> by multiplying the change in <span class="math inline">\(x\)</span> by <span class="math inline">\(m\)</span>.</p>
<p>Consider the following equation for an arbitrary line:</p>
<p><span class="math display">\[y = 5x + 10\]</span></p>
<p>Here are some questions we can now answer:</p>
<ul>
<li>How much does <span class="math inline">\(y\)</span> change if <span class="math inline">\(x\)</span> increases by 1? Answer: 5</li>
<li>How much does <span class="math inline">\(y\)</span> change if <span class="math inline">\(x\)</span> increases by 10? Answer: 50</li>
<li>How much does <span class="math inline">\(y\)</span> change if <span class="math inline">\(x\)</span> decreases by 10? Answer: -50</li>
<li>What does <span class="math inline">\(y\)</span> equal if <span class="math inline">\(x\)</span> equals 2? Answer: 20</li>
<li>What would <span class="math inline">\(y\)</span> equal if <span class="math inline">\(x\)</span> were 0? Answer: 10</li>
</ul>
<p>If you understand how to answer the above questions, then you can interpret regression results for any given context because interpreting regression results involves either predicting the <em>change</em> in <span class="math inline">\(y\)</span> given a <em>change</em> in <span class="math inline">\(x\)</span> or predicting the <em>value</em> of <span class="math inline">\(y\)</span> given a <em>value</em> of <span class="math inline">\(x\)</span>.</p>
<p>What is different in regression is how the equation of line is presented because there are population and sample versions of the relationship between <span class="math inline">\(x\)</span> and <span class="math inline">\(y\)</span>. And, unlike a deterministic mathematical equation like the one above, because we generally use regression to measure relationships between social phenomena, there is inherent uncertainty in the line we calculate. This adds some complexity beyond solving a line’s equation, but the process of running a regression to estimate the slope and intercept of a line to then predict changes or values of an outcome is fundamentally the same as the simple equation above.</p>
</div>
<div id="simple-linear-regression" class="section level2">
<h2><span class="header-section-number">6.3</span> Simple linear regression</h2>
<p>Equation <a href="6-simple-and-multiple-regression.html#eq:simreg">(6.2)</a> presents the population regression model.</p>
<p><span class="math display" id="eq:simreg">\[\begin{equation}
y=\beta_0+\beta_1x+\epsilon
\tag{6.2}
\end{equation}\]</span></p>
<p>Only one element differs between Equations <a href="6-simple-and-multiple-regression.html#eq:line">(6.1)</a> and <a href="6-simple-and-multiple-regression.html#eq:simreg">(6.2)</a>. That is the symbol at the end, which is the Greek letter epsilon and is used to denote the aforementioned uncertainty of predicting real-world, particularly social, phenomena (more on that later).</p>
<p>The y-intercept denoted as <span class="math inline">\(b\)</span> in Equation <a href="6-simple-and-multiple-regression.html#eq:line">(6.1)</a> has been moved to the front of the right-hand side in Equation <a href="6-simple-and-multiple-regression.html#eq:simreg">(6.2)</a> and is denoted by <span class="math inline">\(\beta_0\)</span> (pronounced beta-naught). The slope denoted as <span class="math inline">\(m\)</span> in Equation <a href="6-simple-and-multiple-regression.html#eq:line">(6.1)</a> is now denoted as <span class="math inline">\(\beta_1\)</span> in Equation <a href="6-simple-and-multiple-regression.html#eq:simreg">(6.2)</a>. These beta, <span class="math inline">\(\beta\)</span>, symbols are simply the standard notation for <strong>population parameters</strong> in a statistical model and are used to signal that we intend to estimate these parameters using regression.</p>
<p>Recall that a parameter is a statistical measure of a population. In most cases, our research questions concern a population so large or inaccessible such that we do not observe all members. Instead, we take a sample of the population. From this sample, we calculate sample statistics, or <strong>estimates</strong> of the parameters and use methods of inference to decide if these estimates are valid guesses of the parameter (more on this later).</p>
<p>Equation <a href="6-simple-and-multiple-regression.html#eq:simregsample">(6.3)</a> presents the sample regression equation.</p>
<p><span class="math display" id="eq:simregsample">\[\begin{equation}
\hat{y}=b_0+b_1x
\tag{6.3}
\end{equation}\]</span></p>
<p>The carrot symbol atop our outcome variable <span class="math inline">\(y\)</span> is called a hat, and so the term on the left-hand side is commonly referred to as “y-hat.” This is used to denote the fact that any value we calculate from Equation <a href="6-simple-and-multiple-regression.html#eq:simregsample">(6.3)</a> is an <em>estimate</em> of what has been or will be observed. Similarly, the <span class="math inline">\(b\)</span> symbols are the sample estimate analogs of the <span class="math inline">\(\beta\)</span> population parameters in Equation <a href="6-simple-and-multiple-regression.html#eq:simreg">(6.2)</a>.</p>
<p>Equation <a href="6-simple-and-multiple-regression.html#eq:simregsample">(6.3)</a> is the equation we use to interpret our regression results in the same way as was demonstrated using the mathematical equation of a line. Again, the only difference is that we are dealing with a statistical or probabilistic equation of a line–the outcome we calculate is a prediction based on observed data.</p>
<div id="using-regression" class="section level3">
<h3><span class="header-section-number">6.3.1</span> Using regression</h3>
<p>Let’s pause the theory to consider a simple example using data for U.S. counties. Table <a href="6-simple-and-multiple-regression.html#tab:countydata">6.1</a> provides a preview of the data</p>
<table>
<caption>
<span id="tab:countydata">Table 6.1: </span>Preview of county data
</caption>
<thead>
<tr>
<th style="text-align:left;">
name
</th>
<th style="text-align:left;">
state
</th>
<th style="text-align:right;">
fed_spend
</th>
<th style="text-align:right;">
poverty
</th>
<th style="text-align:right;">
homeownership
</th>
<th style="text-align:right;">
income
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;">
Traverse County
</td>
<td style="text-align:left;">
Minnesota
</td>
<td style="text-align:right;">
20.038786
</td>
<td style="text-align:right;">
9.3
</td>
<td style="text-align:right;">
80.3
</td>
<td style="text-align:right;">
41287
</td>
</tr>
<tr>
<td style="text-align:left;">
Wabash County
</td>
<td style="text-align:left;">
Illinois
</td>
<td style="text-align:right;">
7.422533
</td>
<td style="text-align:right;">
13.0
</td>
<td style="text-align:right;">
80.1
</td>
<td style="text-align:right;">
46026
</td>
</tr>
<tr>
<td style="text-align:left;">
Pike County
</td>
<td style="text-align:left;">
Mississippi
</td>
<td style="text-align:right;">
9.091897
</td>
<td style="text-align:right;">
25.3
</td>
<td style="text-align:right;">
72.9
</td>
<td style="text-align:right;">
30779
</td>
</tr>
<tr>
<td style="text-align:left;">
Greenbrier County
</td>
<td style="text-align:left;">
West Virginia
</td>
<td style="text-align:right;">
9.029030
</td>
<td style="text-align:right;">
19.4
</td>
<td style="text-align:right;">
75.0
</td>
<td style="text-align:right;">
33732
</td>
</tr>
<tr>
<td style="text-align:left;">
Ray County
</td>
<td style="text-align:left;">
Missouri
</td>
<td style="text-align:right;">
5.795480
</td>
<td style="text-align:right;">
9.4
</td>
<td style="text-align:right;">
78.7
</td>
<td style="text-align:right;">
53343
</td>
</tr>
<tr>
<td style="text-align:left;">
Hamilton County
</td>
<td style="text-align:left;">
Tennessee
</td>
<td style="text-align:right;">
10.188056
</td>
<td style="text-align:right;">
14.7
</td>
<td style="text-align:right;">
65.5
</td>
<td style="text-align:right;">
45408
</td>
</tr>
<tr>
<td style="text-align:left;">
Ballard County
</td>
<td style="text-align:left;">
Kentucky
</td>
<td style="text-align:right;">
11.907989
</td>
<td style="text-align:right;">
13.0
</td>
<td style="text-align:right;">
83.3
</td>
<td style="text-align:right;">
41228
</td>
</tr>
</tbody>
</table>
<p>where <code>fed_spending</code> is the amount of federal funds allocated to the county per capita, <code>poverty</code> is the percent of the population in poverty, <code>homeownership</code> is the percent of the population that owns a home, and <code>income</code> is per capita income. There are 3,143 observations in this dataset.</p>
<p>Suppose we wanted to examine the association between federal spending and poverty for U.S. counties such that poverty <em>explains</em> federal spending. After all, a substantial portion of federal dollars are dedicated to assist those in poverty. First, we might visualize the relationship between the two variables.</p>
<div class="figure"><span id="fig:povfedscatter"></span>
<img src="data-apps-text_files/figure-html/povfedscatter-1.png" alt="Federal spending and poverty among U.S. counties" width="672" />
<p class="caption">
Figure 6.1: Federal spending and poverty among U.S. counties
</p>
</div>
<p>If we were to trace a line through these points, it would clearly slope upward. Thus, this suggests to us that as the percent of the population of a county increases, the amount of federal spending it receives increases. But by how much? That is precisely what regression estimates for us.</p>
<p>Equation <a href="6-simple-and-multiple-regression.html#eq:simregexample">(6.4)</a> represents the relationship between federal spending and poverty using a simple linear regression population model. Note that we have chosen to model the two variables such that poverty explains or predicts federal spending. This aligns with the choice to plot poverty on the x axis and federal spending on the y axis in Figure <a href="6-simple-and-multiple-regression.html#fig:povfedscatter">6.1</a>. This is a critical choice in every regression and one that computers still need humans to help with (more on that later).</p>
<p><span class="math display" id="eq:simregexample">\[\begin{equation}
FedSpend = \beta_0+\beta_1Poverty + \epsilon
\tag{6.4}
\end{equation}\]</span></p>
<p>We are going to use observed values of poverty and federal spending to estimate <span class="math inline">\(\beta_0\)</span> and <span class="math inline">\(beta_1\)</span>. Then, once we have those estimates, we can provide succinct answers regarding how federal spending tends to change given a change in poverty or a predicted level of federal spending given a particular level of poverty in a county.</p>
<p>The <span class="math inline">\(\epsilon\)</span> represents all the other factors that explain or predict federal spending that are not in our model. If our world were such that the points in <a href="6-simple-and-multiple-regression.html#fig:povfedscatter">6.1</a> literally formed a straight line, we would not need an <span class="math inline">\(\epsilon\)</span>, but this is never the case with interesting questions of complex phenomena. This may or may not be a problem for whatever story we intend to tell about the the relationship between poverty and federal spending (more on that later).</p>
<p>Running the regression as represented in Equation <a href="6-simple-and-multiple-regression.html#eq:simregexample">(6.4)</a> produces Table <a href="6-simple-and-multiple-regression.html#tab:simpregextab">6.2</a> of results.</p>
<table>
<caption>
<span id="tab:simpregextab">Table 6.2: </span>Regression results of poverty on federal spending
</caption>
<thead>
<tr>
<th style="text-align:left;">
term
</th>
<th style="text-align:right;">
estimate
</th>
<th style="text-align:right;">
std_error
</th>
<th style="text-align:right;">
statistic
</th>
<th style="text-align:right;">
p_value
</th>
<th style="text-align:right;">
lower_ci
</th>
<th style="text-align:right;">
upper_ci
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;">
intercept
</td>
<td style="text-align:right;">
7.950
</td>
<td style="text-align:right;">
0.219
</td>
<td style="text-align:right;">
36.294
</td>
<td style="text-align:right;">
0
</td>
<td style="text-align:right;">
7.520
</td>
<td style="text-align:right;">
8.379
</td>
</tr>
<tr>
<td style="text-align:left;">
poverty
</td>
<td style="text-align:right;">
0.108
</td>
<td style="text-align:right;">
0.013
</td>
<td style="text-align:right;">
8.265
</td>
<td style="text-align:right;">
0
</td>
<td style="text-align:right;">
0.082
</td>
<td style="text-align:right;">
0.134
</td>
</tr>
</tbody>
</table>
<p>With the exception of Chapter @(causation), this section on regression models focuses on understanding the methods used to generate the values in the <code>estimate</code> column immediately to the right of the variable names as well as how to interpret and apply these values to any question. The remaining columns in the above table pertain to inference. The values in the <code>estimate</code> column are commonly referred to as <strong>coefficients</strong>, which were first mentioned in Chapter <a href="4-descriptive-statistics.html#descriptive-statistics">4</a>. Regression coefficients measure the direction and magnitude of association between an explanatory variable and an outcome variable.</p>
<p>Now that we have our results, we can plug them into our sample regression equation like so</p>
<p><span class="math display" id="eq:simregresults">\[\begin{equation}
\hat{FedSpend}=7.95+0.11 \times Poverty
\tag{6.5}
\end{equation}\]</span></p>
<p>and we are back to the first section of this chapter. Given a change in poverty we can predict the change in federal spending. Given any particular poverty level, we can predict a level of federal spending.</p>
<p>As for a standard template to interpret regression results, we generally say or write the following,</p>
<blockquote>
<p>On average, as the percent of the population in poverty increases by 1 percentage point, federal spending per capita increases approximately 11 cents.</p>
</blockquote>
<p>A couple points about the above template:</p>
<ul>
<li>We always qualify using “on average” because that is exactly what regression does. Drawing a line through a scatter plot results in points above and below that line. The line drawn by regression traces how <span class="math inline">\(y\)</span> responds to <span class="math inline">\(x\)</span> <em>on average</em>.</li>
<li>The standard change in <span class="math inline">\(x\)</span> to use when reporting results is one unit. Poverty is in units of percent. Therefore, a one-unit change in a variable measured in percentages is one percentage point (e.g. 10% to 11%).</li>
</ul>
<p>However, we could report these results using any change or particular value in poverty germane to our original research question. For example, if we expected a county’s poverty rate to be 30%, then we could report a predicted level of federal spending per capita equal to</p>
<div class="sourceCode" id="cb1"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1-1"><a href="6-simple-and-multiple-regression.html#cb1-1"></a><span class="fl">7.95+0.11</span><span class="op">*</span><span class="dv">30</span></span></code></pre></div>
<pre><code>## [1] 11.25</code></pre>
<p>dollars per capita. Similarly, if we expected a decrease in the poverty rate of 5 percentage points, then we could predict a change in the level of federal spending per capita equal to</p>
<div class="sourceCode" id="cb3"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb3-1"><a href="6-simple-and-multiple-regression.html#cb3-1"></a><span class="fl">0.11</span><span class="op">*-</span><span class="dv">5</span></span></code></pre></div>
<pre><code>## [1] -0.55</code></pre>
<p>dollars per capita.</p>
</div>
<div id="the-error-term" class="section level3">
<h3><span class="header-section-number">6.3.2</span> The error term</h3>
<p>Back to theory. We need to address this <span class="math inline">\(\epsilon\)</span> that is present in the population regression model but disappears in the sample regression model and results. What gives?</p>
<p>The <span class="math inline">\(\epsilon\)</span> term is commonly referred to as the <strong>error term</strong> or, for those who don’t like to insinuate some error was made in the regression, <strong>statistical noise</strong>. I prefer error term if for no other reason than to remind us to consider the myriad of errors we <em>may</em> be making in our regression model.</p>
<p>As mentioned, the error term represents the inherent uncertainty of modeling an outcome based on a necessarily finite number of explanatory factors. Other factors affect our outcome. As a matter of principle, this does not prohibit our attempt to estimate the effect of a variable we care about or can alter with policy or programs on the outcome.</p>
<p>Could we account for multiple factors (i.e. multiple regression)? Absolutely. Can we control for <em>everything</em> that affects our outcome? Definitely not if you subscribe to chaos theory or David Hume’s thoughts on causality. Even if not so extreme as to say our world is too complex to ever make decisions concerning one variable’s effect on another, the plausibility for us to collect data on every relevant factor is highly unlikely.</p>
<p>So, where did the error term go? It never really left; it simply is not used when calculating the predicted outcome based on our regression results. Like our <span class="math inline">\(\beta\)</span> terms, the error term is a population parameter. However, unlike the <span class="math inline">\(\beta\)</span>s, we do not have observed data that corresponds to its estimation. In fact, the concept of the error term exists on the basis that we do not observe it. Therefore, it is necessarily excluded when we predict an outcome based on observed data, all the while we are careful to remind readers that the numbers we report are estimates subject to error.</p>
<p>If the error term never left, where is it? Its sample analog exists as the difference between our estimated regression line and the observed data. Figure <a href="6-simple-and-multiple-regression.html#fig:povfedscatter2">6.2</a> below is the same as Figure <a href="6-simple-and-multiple-regression.html#fig:povfedscatter">6.1</a> except that it displays the line based on our regression results in Table <a href="6-simple-and-multiple-regression.html#tab:simpregextab">6.2</a>.</p>
<div class="figure"><span id="fig:povfedscatter2"></span>
<img src="data-apps-text_files/figure-html/povfedscatter2-1.png" alt="Federal spending and poverty among U.S. counties" width="672" />
<p class="caption">
Figure 6.2: Federal spending and poverty among U.S. counties
</p>
</div>
<p>Surely, it is apparent that our regression line does not intersect all points perfectly; many points lie above and others below it. Pick any point in Figure <a href="6-simple-and-multiple-regression.html#fig:povfedscatter2">6.2</a> and draw a vertical line to the regression line. The length of that line, which in this case is in units of dollars of federal spending per capita, and all other vertical distances between observed points and the regression line, is our sample version of the error term.</p>
<p>Table <a href="6-simple-and-multiple-regression.html#tab:simregexresid">6.3</a> quantifies the error for each of a select few observations.</p>
<table>
<caption>
<span id="tab:simregexresid">Table 6.3: </span>Comparing observed and predicted federal spending
</caption>
<thead>
<tr>
<th style="text-align:right;">
ID
</th>
<th style="text-align:right;">
fed_spend
</th>
<th style="text-align:right;">
poverty
</th>
<th style="text-align:right;">
fed_spend_hat
</th>
<th style="text-align:right;">
residual
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:right;">
1961
</td>
<td style="text-align:right;">
7.592
</td>
<td style="text-align:right;">
16.9
</td>
<td style="text-align:right;">
9.773
</td>
<td style="text-align:right;">
-2.181
</td>
</tr>
<tr>
<td style="text-align:right;">
2440
</td>
<td style="text-align:right;">
10.188
</td>
<td style="text-align:right;">
17.1
</td>
<td style="text-align:right;">
9.795
</td>
<td style="text-align:right;">
0.393
</td>
</tr>
<tr>
<td style="text-align:right;">
1738
</td>
<td style="text-align:right;">
15.784
</td>
<td style="text-align:right;">
8.8
</td>
<td style="text-align:right;">
8.899
</td>
<td style="text-align:right;">
6.885
</td>
</tr>
<tr>
<td style="text-align:right;">
2641
</td>
<td style="text-align:right;">
23.503
</td>
<td style="text-align:right;">
0.0
</td>
<td style="text-align:right;">
7.950
</td>
<td style="text-align:right;">
15.554
</td>
</tr>
<tr>
<td style="text-align:right;">
1471
</td>
<td style="text-align:right;">
8.152
</td>
<td style="text-align:right;">
25.0
</td>
<td style="text-align:right;">
10.647
</td>
<td style="text-align:right;">
-2.495
</td>
</tr>
<tr>
<td style="text-align:right;">
1362
</td>
<td style="text-align:right;">
7.649
</td>
<td style="text-align:right;">
14.0
</td>
<td style="text-align:right;">
9.460
</td>
<td style="text-align:right;">
-1.811
</td>
</tr>
<tr>
<td style="text-align:right;">
2792
</td>
<td style="text-align:right;">
7.933
</td>
<td style="text-align:right;">
13.5
</td>
<td style="text-align:right;">
9.406
</td>
<td style="text-align:right;">
-1.474
</td>
</tr>
</tbody>
</table>
<p>Our regression model uses observed values of poverty and federal spending to estimate the parameters of the regression line, which produced Equation <a href="6-simple-and-multiple-regression.html#eq:simregresults">(6.5)</a>. We can then plug the observed values of poverty into the equation to compute a predicted level of federal spending–<code>fed_spend_hat</code>. But, we know this prediction is not perfect in most cases. The right-most column of Table <a href="6-simple-and-multiple-regression.html#tab:simregexresid">6.3</a> shows the difference between <em>predicted</em> federal spending and <em>observed</em> federal spending. This difference is called the <strong>residual</strong>.</p>
<p>Using the first row of Table <a href="6-simple-and-multiple-regression.html#tab:simregexresid">6.3</a> as an example, our regression predicts a county with 16.9 percent poverty to receive 7.59 dollars per capita in federal spending. However, this county actually received 9.78 dollars per capita. Our regression underestimates federal spending for this county by 2.18 dollars. Thus, the residual for this county is -2.18.</p>
<p>The residual is represented mathematically by Equation <a href="6-simple-and-multiple-regression.html#eq:simregresid">(6.6)</a></p>
<p><span class="math display" id="eq:simregresid">\[\begin{equation}
e = y - \hat{y}
\tag{6.6}
\end{equation}\]</span></p>
<p>where <span class="math inline">\(e\)</span> is the sample analog of <span class="math inline">\(\epsilon\)</span>. This is simply the equation behind the process of differencing the observed and predicted values of our outcome just described.</p>
</div>
<div id="goodness-of-fit" class="section level3">
<h3><span class="header-section-number">6.3.3</span> Goodness of fit</h3>
<p>Armed with an understanding of error and its sample analog, the residual, we can now consider goodness-of-fit. We must accept there will be error in our regression, but that does not mean we do not seek to minimize that error as much as possible.</p>
<div id="assessing-fit" class="section level4 unnumbered">
<h4>Assessing fit</h4>
<p>Table <a href="6-simple-and-multiple-regression.html#tab:simregexfit">6.4</a> provides a standard set of three goodness-of-fit measures often used to assess regression.</p>
<table>
<caption>
<span id="tab:simregexfit">Table 6.4: </span>Goodness-of-fit measures
</caption>
<thead>
<tr>
<th style="text-align:right;">
r_squared
</th>
<th style="text-align:right;">
adj_r_squared
</th>
<th style="text-align:right;">
rmse
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:right;">
0.021
</td>
<td style="text-align:right;">
0.021
</td>
<td style="text-align:right;">
4.654482
</td>
</tr>
</tbody>
</table>
<p>The first column titled <code>r_squared</code> refers to the measure <span class="math inline">\(R^2\)</span>, also known as the <strong>coefficient of determination</strong> defined in <a href="4-descriptive-statistics.html#descriptive-statistics">4</a>. The <span class="math inline">\(R^2\)</span> measures the strength of association between a set of one or more explanatory variables and an outcome variable. Specifically, it quantifies the percent of total variation in the outcome explained by our regression model. In this case, our regression using poverty explains 2.1% of the total variation in federal spending.</p>
<p>The column titled <code>rmse</code> refers to <strong>root mean squared error</strong> (RMSE). The RMSE quantifies the typical deviation of the observed data points from the regression line and is particularly useful when predicting a value for our outcome. For example, if after predicting that a county with 30% poverty will receive 11.25 dollars of federal spending per capita, someone asks us how far off that prediction is likely to be, the RMSE suggests our prediction will tend to be off by plus or minus 4.65 dollars.</p>
<p>Regression involves choices. We choose which variables to use to explain or predict an outcome and how to model their effect on the outcome. This menu of choices will become increasingly evident as we build our regression toolbox. As we make choices, competing regression models emerge from which we must choose the one we prefer to report for decision-making.</p>
<p>The <span class="math inline">\(R^2\)</span> and RMSE provide us the basis for choosing our preferred model. In general, <strong>we prefer the model with a <em>higher</em> <span class="math inline">\(R^2\)</span> and/or a lower <em>RMSE</em></strong>. In virtually all cases, these two measures will agree with each other; the model with the higher <span class="math inline">\(R^2\)</span> will also have the lower RMSE.</p>
</div>
<div id="understanding-fit" class="section level4 unnumbered">
<h4>Understanding fit</h4>
<div class="announcement">
<p>
The material under this header is nonessential but is included because a deeper understanding of the mechanics of fit can be helpful.
</p>
</div>
<p>Regression draws the <em>best</em> line through a set of data points of two or more variables. The best line in this case is the line with a slope and y-intercept that <strong>minimizes the sum of squared residual</strong> between the set of data points and said line. The procedure used to achieve such a line is called <strong>ordinary least squares</strong> (OLS). The type of regression covered in this book is sometimes referred to as OLS regression.</p>
<p>Recall that the variance of a variable is the sum of squared deviations from the mean, as depicted in Equation <a href="4-descriptive-statistics.html#eq:variance">(4.2)</a>. This should sound familiar. Instead of deviations from the mean, fitting the best line in regression concerns the deviations from the regression line, which by definition are the residuals. As with variance, we square the deviations (i.e. residuals) for the data used to estimate the regression line, then we add these squared deviations together to obtain the sum of squared residual (SSR). Equation <a href="6-simple-and-multiple-regression.html#eq:ssr">(6.7)</a> shows this process mathematically.</p>
<p><span class="math display" id="eq:ssr">\[\begin{equation}
SSR=\sum _{i=1}^{n}(y_{i}-\hat{y})^2= (y_{1}-\hat{y})^2+(y_{2}-\hat{y})^2+\cdots +(y_{n}-\hat{y})^2
\tag{6.7}
\end{equation}\]</span></p>
<p>SSR quantifies the error in our regression and is what regression minimizes when predicting an outcome given the explanatory variables we have chosen to include.</p>
<p>The SSR also provides us what we need to compute the root mean squared error (RMSE). Recall that in order to compute the variance and standard deviation of a variable in Equations <a href="4-descriptive-statistics.html#eq:variance">(4.2)</a> and <a href="4-descriptive-statistics.html#eq:sd">(4.3)</a>, respectively, we divide the sum of squared deviations by the number of observations (or <span class="math inline">\(n-1\)</span>) then take the square root. The SSR is a sum of squared deviations. The deviations in this case represent error. If we divide SSR by the number of observations, we now have the mean of the sum of squared error. Then, if we take the square root, we have the root mean squared error. Note that this is the same process used to obtain the standard deviation. Thus, the RMSE is the regression version of a standard deviation. Just as the standard deviation tells us the average deviation from the mean, the RMSE tells us the average deviation from the regression line, or the average error in our regression.</p>
<p>We can also quantify the extent to which our regression <em>explains</em> the outcome. To do so, we need a benchmark against which to compare the reduction in error achieved by our regression. This benchmark is simply the average value of the outcome. If we had no explanatory variables to predict an outcome, the mean provides the typical value of the outcome. If we had to draw a random observation from a variable’s distribution, the mean is our best guess of what that observation’s value would be if we have no explanatory variables.</p>
<p>Figure <a href="6-simple-and-multiple-regression.html#fig:povfedscatter3">6.3</a> adds a reference line of average federal spending to our scatter plot. Note that because average federal spending is a constant number, it does not change as poverty changes; the red line has no slope. Also, note that the red line does slightly worse fitting the data, particularly toward the left and right extremes of poverty. Compared to the red line representing the mean, the data appear to be more centered around our regression line. As a result, our regression line has less error than the mean.</p>
<div class="figure"><span id="fig:povfedscatter3"></span>
<img src="data-apps-text_files/figure-html/povfedscatter3-1.png" alt="Federal spending and poverty among U.S. counties" width="672" />
<p class="caption">
Figure 6.3: Federal spending and poverty among U.S. counties
</p>
</div>
<p>The mean of the outcome is our benchmark for assessing how much the explanatory variables included in our regression model explains the total variation in the outcome. The difference, if any, between the values our regression predicts, <span class="math inline">\(\hat{y_i}\)</span>, and the mean, <span class="math inline">\(\bar{y}\)</span>, serves as the basis for quantifying the extent to which our regression model explains the total variation in the outcome. Just like with the SSR, we square the difference between each predicted value and the mean, then add them together. The result is called the <strong>sum of squared explained</strong> (SSE) and is represented mathematically in Equation <a href="6-simple-and-multiple-regression.html#eq:sse">(6.8)</a>.</p>
<p><span class="math display" id="eq:sse">\[\begin{equation}
SSE=\sum _{i=1}^{n}(\hat{y}_{i}-\bar{y})^2= (\hat{y}_{1}-\bar{y})^2+(\hat{y}_{2}-\bar{y})^2+\cdots +(\hat{y}_{n}-\bar{y})^2
\tag{6.8}
\end{equation}\]</span></p>
<p>We now have the sum of squared residuals (SSR) and sum of squared explained (SSE). Together, the SSR and SSE represent the <strong>sum of squared total</strong> (SST) variation in the outcome <span class="math inline">\(y\)</span>.</p>
<p><span class="math display" id="eq:sst">\[\begin{equation}
SST = SSR + SSE
\tag{6.9}
\end{equation}\]</span></p>
<p>Recall that the <span class="math inline">\(R^2\)</span> measures the percent of total variation in the outcome that is explained by our regression. To calculate any percent we take divide a proportion of the whole divided by the whole (e.g. <span class="math inline">\(5/10 = 0.5\)</span> or 50%). Thus, to obtain the percent of variation in the outcome explained by our regression, we divide the SSE by SST.</p>
<p><span class="math display" id="eq:r2">\[\begin{equation}
R^2 = {\frac{SSE}{SST}}
\tag{6.10}
\end{equation}\]</span></p>
<p>The better you understand the mechanics of simple linear regression, the easier it will be to understand the next section and subsequent chapters on regression models because they are mere extensions of this basic model.</p>
</div>
</div>
</div>
<div id="multiple-regression" class="section level2">
<h2><span class="header-section-number">6.4</span> Multiple regression</h2>
<p>Of course, we are not limited to using only one variable to explain or predict an outcome. In fact, it is rather uncommon to use only one variable, but simple linear regression is useful for introducing the method of regression. Now, we can consider more realistic modeling method where we use multiple explanatory variables in our regression, which is aptly named multiple regression.</p>
<p>Equation <a href="6-simple-and-multiple-regression.html#eq:multreg">(6.11)</a> provides the population model for multiple regression</p>
<p><span class="math display" id="eq:multreg">\[\begin{equation}
y=\beta_0+\beta_1x_1+\beta_2x_2+\cdots+\beta_kx_k+\epsilon
\tag{6.11}
\end{equation}\]</span></p>
<p>The only difference in this equation compared to Equation <a href="6-simple-and-multiple-regression.html#eq:simreg">(6.2)</a> is the inclusion of multiple explanatory variables. Each explanatory is numbered and has a corresponding parameter <span class="math inline">\(\beta\)</span> representing the marginal effect it has on the outcome. In theory, we can add however many explanatory variables we deem worth including, represented by the arbitrary <span class="math inline">\(k\)</span>.</p>
<p>Equation <a href="6-simple-and-multiple-regression.html#eq:multregsample">(6.12)</a> presents the sample equation for multiple regression.</p>
<p><span class="math display" id="eq:multregsample">\[\begin{equation}
\hat{y}=b_0+b_1x_1+b_2x_2+\cdots +b_kx_k
\tag{6.12}
\end{equation}\]</span></p>
<p>Again, nothing is different from before except for more explanatory variables and sample estimates of the parameters.</p>
<div id="using-multiple-regression" class="section level3">
<h3><span class="header-section-number">6.4.1</span> Using multiple regression</h3>
<p>Let’s return to our example of federal spending per capita in U.S. counties. Previously, we used only the percent of the population in poverty to explain or predict federal spending per capita. Let’s add the percent of the population that owns a home and per capita income to our model. Thus, our model can be written as such</p>
<p><span class="math display" id="eq:multregex">\[\begin{equation}
FedSpend = \beta_0 + \beta_1Poverty + \beta_2HomeOwn + \beta_3Income + \epsilon
\tag{6.13}
\end{equation}\]</span></p>
<p>which generates the following results</p>
<table>
<caption>
<span id="tab:multregextab">Table 6.5: </span>Multiple regression results
</caption>
<thead>
<tr>
<th style="text-align:left;">
term
</th>
<th style="text-align:right;">
estimate
</th>
<th style="text-align:right;">
std_error
</th>
<th style="text-align:right;">
statistic
</th>
<th style="text-align:right;">
p_value
</th>
<th style="text-align:right;">
lower_ci
</th>
<th style="text-align:right;">
upper_ci
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;">
intercept
</td>
<td style="text-align:right;">
23.519
</td>
<td style="text-align:right;">
1.333
</td>
<td style="text-align:right;">
17.645
</td>
<td style="text-align:right;">
0.000
</td>
<td style="text-align:right;">
20.905
</td>
<td style="text-align:right;">
26.132
</td>
</tr>
<tr>
<td style="text-align:left;">
poverty
</td>
<td style="text-align:right;">
-0.056
</td>
<td style="text-align:right;">
0.021
</td>
<td style="text-align:right;">
-2.674
</td>
<td style="text-align:right;">
0.008
</td>
<td style="text-align:right;">
-0.097
</td>
<td style="text-align:right;">
-0.015
</td>
</tr>
<tr>
<td style="text-align:left;">
homeownership
</td>
<td style="text-align:right;">
-0.126
</td>
<td style="text-align:right;">
0.012
</td>
<td style="text-align:right;">
-10.736
</td>
<td style="text-align:right;">
0.000
</td>
<td style="text-align:right;">
-0.149
</td>
<td style="text-align:right;">
-0.103
</td>
</tr>
<tr>
<td style="text-align:left;">
income
</td>
<td style="text-align:right;">
0.000
</td>
<td style="text-align:right;">
0.000
</td>
<td style="text-align:right;">
-7.723
</td>
<td style="text-align:right;">
0.000
</td>
<td style="text-align:right;">
0.000
</td>
<td style="text-align:right;">
0.000
</td>
</tr>
</tbody>
</table>
<p>and the following goodness-of-fit measures</p>
<table>
<caption>
<span id="tab:multregexfit">Table 6.6: </span>Fit of multiple regression
</caption>
<thead>
<tr>
<th style="text-align:right;">
r_squared
</th>
<th style="text-align:right;">
adj_r_squared
</th>
<th style="text-align:right;">
rmse
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:right;">
0.064
</td>
<td style="text-align:right;">
0.063
</td>
<td style="text-align:right;">
4.55216
</td>
</tr>
</tbody>
</table>
<p>Now we can discuss what is different with multiple regression. First, note that our coefficient or estimate for poverty has changed from 0.108 to 0.105. A small difference to be sure, but that is specific to the example used; sometimes the estimate can change dramatically. Why the change? Because we are <strong>controlling for other factors</strong>. A slight amount of the marginal effect we reported poverty had on federal spending in our simple regression model was misattributed from the marginal effects of homeownership and/or income on federal spending.</p>
<p>This is a key feature of multiple regression: it estimates the marginal effect of a variable on an outcome, holding all other explanatory variables equal to their respective means. In other words, if we were omnipotent beings who could take each county in our data and set homeownership and income to the mean of homeownership and income according to the observed data, then pull some lever that makes poverty change and nothing else, the estimate for poverty in our multiple regression reports how much each percentage point in poverty changes federal spending. This is how we isolate the effect of one variable on an outcome despite knowing other variables simultaneously affect our outcome.</p>
<p>The interpretation of multiple regression estimates is essentially the same as simple regression. In our example, we can interpret the homeownership estimate like so:</p>
<blockquote>
<p>On average, our results indicate that a one percentage point increase in the percent of the population that owns a home is associated with a decrease in federal spending per capita of approximately 9 cents, <strong>holding other factors constant</strong>.</p>
</blockquote>
<p>The part in bold is to point out the small difference between the two interpretations. Here, we are simply reminding a reader that we have controlled for other factors that presumably we have already explained, and our estimate for poverty accounts for those factors by holding them constant. Other common word choices for this part of the interpretation include “all else equal” or its Latin translation “ceteris paribus.”</p>
<p>Again, we can answer any sort of question relevant to our original research question concerning the predicted change or level of federal spending by plugging in the numbers to our regression equation.</p>
<p><span class="math display">\[\begin{equation}
\hat{FedSpend} = 13.50 + 0.105\times Poverty - 0.093\times HomeOwn + 0Income
\end{equation}\]</span></p>
<p>If we wanted to predict the change in federal spending given an 3 percentage point increase in poverty and a decline in home ownership of 4 percentage points, the our answer would be</p>
<div class="sourceCode" id="cb5"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb5-1"><a href="6-simple-and-multiple-regression.html#cb5-1"></a><span class="fl">0.105</span><span class="op">*</span><span class="dv">3</span><span class="op">+</span>(<span class="op">-</span><span class="fl">0.093</span>)<span class="op">*</span>(<span class="op">-</span><span class="dv">4</span>)</span></code></pre></div>
<pre><code>## [1] 0.687</code></pre>
<p>dollars per capita (on average and all else equal, of course). If we wanted to predict the level of federal spending per capita for a county with 12% poverty, a 80% home ownership rate, and $31,000 income per capita, then we would predict</p>
<div class="sourceCode" id="cb7"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb7-1"><a href="6-simple-and-multiple-regression.html#cb7-1"></a><span class="fl">13.50+0.105</span><span class="op">*</span><span class="dv">12</span><span class="fl">-0.093</span><span class="op">*</span><span class="dv">80</span><span class="op">+</span><span class="dv">0</span><span class="op">*</span><span class="dv">31000</span></span></code></pre></div>
<pre><code>## [1] 7.32</code></pre>
<p>dollars per capita.</p>
<p>Not so fast! This example provides a good opportunity to consider another aspect of the units our variables are in. Per capita income is in dollars. This means the estimate for income represents the effect of a <em>one dollar</em> change in per capita income on federal spending per capita. That’s a very small change that we would expect to have a very small effect on federal spending. This effect is so small that statistical software may round to 0. But what if we changed the units of income to <em>thousands</em> of dollars per capita instead of dollars per capita? Then we get the following results.</p>
<table>
<thead>
<tr>
<th style="text-align:left;">
term
</th>
<th style="text-align:right;">
estimate
</th>
<th style="text-align:right;">
std_error
</th>
<th style="text-align:right;">
statistic
</th>
<th style="text-align:right;">
p_value
</th>
<th style="text-align:right;">
lower_ci
</th>
<th style="text-align:right;">
upper_ci
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;">
intercept
</td>
<td style="text-align:right;">
23.519
</td>
<td style="text-align:right;">
1.333
</td>
<td style="text-align:right;">
17.645
</td>
<td style="text-align:right;">
0.000
</td>
<td style="text-align:right;">
20.905
</td>
<td style="text-align:right;">
26.132
</td>
</tr>
<tr>
<td style="text-align:left;">
poverty
</td>
<td style="text-align:right;">
-0.056
</td>
<td style="text-align:right;">
0.021
</td>
<td style="text-align:right;">
-2.674
</td>
<td style="text-align:right;">
0.008
</td>
<td style="text-align:right;">
-0.097
</td>
<td style="text-align:right;">
-0.015
</td>
</tr>
<tr>
<td style="text-align:left;">
homeownership
</td>
<td style="text-align:right;">
-0.126
</td>
<td style="text-align:right;">
0.012
</td>
<td style="text-align:right;">
-10.736
</td>
<td style="text-align:right;">
0.000
</td>
<td style="text-align:right;">
-0.149
</td>
<td style="text-align:right;">
-0.103
</td>
</tr>
<tr>
<td style="text-align:left;">
income
</td>
<td style="text-align:right;">
-0.086
</td>
<td style="text-align:right;">
0.011
</td>
<td style="text-align:right;">
-7.723
</td>
<td style="text-align:right;">
0.000
</td>
<td style="text-align:right;">
-0.108
</td>
<td style="text-align:right;">
-0.064
</td>
</tr>
</tbody>
</table>
<p>Now we see the effect of a <em>one thousand</em> dollar change in per capita income on federal spending per capita. Note that the estimates for poverty and homeownership are the same. Therefore, the predicted level of federal spending for our county is actually</p>
<div class="sourceCode" id="cb9"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb9-1"><a href="6-simple-and-multiple-regression.html#cb9-1"></a><span class="fl">13.50+0.105</span><span class="op">*</span><span class="dv">12</span><span class="fl">-0.093</span><span class="op">*</span><span class="dv">80</span><span class="fl">+0.057</span><span class="op">*</span><span class="dv">31</span></span></code></pre></div>
<pre><code>## [1] 9.087</code></pre>
</div>
<div id="fit-and-adjusted-r-squared" class="section level3">
<h3><span class="header-section-number">6.4.2</span> Fit and adjusted R squared</h3>
<p>In addition to doing a better job isolating the marginal effect of one variable on an outcome, including additional explanatory variables can reduce the error in our regression, thus achieve more accurate and/or precise predictions of the outcome.</p>
<p>We can assess this improvement in fit by comparing the results in Table <a href="6-simple-and-multiple-regression.html#tab:multregexfit">6.6</a> to those in Table <a href="6-simple-and-multiple-regression.html#tab:simregexfit">6.4</a>. We have gone from an RMSE of 4.65 dollars to an RMSE 4.59 dollars. This means our predictions from the multiple regression model tend to be off by 6 cents fewer than the predictions of our simple regression model.</p>
<p>The previous discussion on fit conspicuously skipped over the column titled <code>adj_r_square</code> because <strong>adjusted-<span class="math inline">\(R^2\)</span></strong> applies when comparing two or more models with a different number of explanatory variables. One caveat to using <span class="math inline">\(R^2\)</span> to choose a preferred model is that it mechanically increases as the number of explanatory variables increases whether those additional variables improve the extent to which our regression explains the total variation in the outcome or not. Therefore, it is unfair to compare a model with one explanatory variable to a model with more than one explanatory variable.</p>
<p>The adjusted-<span class="math inline">\(R^2\)</span> accounts for this unfairness by applying a penalty to each additional explanatory variable. We can fairly compare models with different numbers of explanatory variables using their respective adjusted-<span class="math inline">\(R^2\)</span>. In our example, we have gone from explaining 2.1% of the total variation in federal spending to explaining 4.7% of its total variation. Adding home ownership and income has more than doubled the explanatory power of our model of federal spending.</p>
</div>
<div id="explanatory-penalty" class="section level3">
<h3><span class="header-section-number">6.4.3</span> Explanatory penalty</h3>
<p>Each explanatory variable we add to our regression model imposes a type of penalty on our results. Basically, for each explanatory variable included, we lose an observation in our data (not literally). This will be discussed further in the section on inference, but we need at least 33 observations to make valid inferences about a population based on sample estimates. If we had, say 50 observations in a dataset, and wanted to run a regression with 25 explanatory variables, then it is as though our regression model is based on only 25 observations (50 observations - 25 variables = 25 degrees of freedom). We will obtain results from such a model, but we should not use those results to make inferences.</p>
<p>In case you were wondering why not simply add all the variables we can to a model rather than carefully consider which variables to include and exclude in a model, this penalty is one of the primary reasons. Fewer degrees of freedom jeopardizes our ability to make valid inference. It can also reduce the precision of our predictions. The goal is to maximize the explanatory or predictive power of our regression model at minimal cost (i.e. excluding superfluous variables). Choosing good regression models is where subject matter expertise plays a crucial role. Experience and knowledge within the context of the research question informs our choices. Statistics is the method by which we apply our expertise to data to make evidence-based decisions.</p>
<p><br></p>
<blockquote>
<p><strong>To learn how to run regression in R, proceed to Chapter <a href="22-r-regression.html#r-regression">22</a>.</strong></p>
</blockquote>
</div>
</div>
<div id="kt6" class="section level2">
<h2><span class="header-section-number">6.5</span> Key terms and concepts</h2>
<div class="learncheck">
<ul>
<li>
Line concepts
<ul>
<li>
y-intercept
</li>
<li>
slope
</li>
<li>
change in y versus value of y
</li>
</ul>
</li>
<li>
Regression model components
<ul>
<li>
outcome/dependent/response variable
</li>
<li>
independent/explanatory variable
</li>
<li>
error term/statistical noise
</li>
<li>
residual
</li>
<li>
population parameter
</li>
<li>
sample coefficients/estimates
</li>
</ul>
</li>
<li>
Goodness of fit
<ul>
<li>
R-squared
</li>
<li>
Adjusted R-squared
</li>
<li>
root mean squared error (RMSE)
</li>
</ul>
</li>
<li>
Controlling for other factors in multiple regression
</li>
</ul>
</div>

</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="5-data-visualization.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="7-categorical-variables-and-interactions.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/lunr.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": false,
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": null,
"text": null
},
"history": {
"link": null,
"text": null
},
"view": {
"link": null,
"text": null
},
"download": null,
"toc": {
"collapse": "section"
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
