<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title> 8 Nonlinear Variables | Data Applications in Public Administration</title>
  <meta name="description" content="Companion text for PADP 7120" />
  <meta name="generator" content="bookdown 0.20 and GitBook 2.6.7" />

  <meta property="og:title" content=" 8 Nonlinear Variables | Data Applications in Public Administration" />
  <meta property="og:type" content="book" />
  <meta property="og:url" content="https://alex-combs.github.io/data-apps-text/" />
  
  <meta property="og:description" content="Companion text for PADP 7120" />
  <meta name="github-repo" content="alex-combs/data-apps-text" />

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content=" 8 Nonlinear Variables | Data Applications in Public Administration" />
  
  <meta name="twitter:description" content="Companion text for PADP 7120" />
  

<meta name="author" content="Alex Combs" />



  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="7-categorical-variables-and-interactions.html"/>
<link rel="next" href="9-causation-and-bias.html"/>
<script src="libs/jquery-2.2.3/jquery.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />









<script src="libs/accessible-code-block-0.0.1/empty-anchor.js"></script>
<script src="libs/htmlwidgets-1.5.1/htmlwidgets.js"></script>
<link href="libs/datatables-css-0.0.0/datatables-crosstalk.css" rel="stylesheet" />
<script src="libs/datatables-binding-0.14/datatables.js"></script>
<link href="libs/dt-core-1.10.20/css/jquery.dataTables.min.css" rel="stylesheet" />
<link href="libs/dt-core-1.10.20/css/jquery.dataTables.extra.css" rel="stylesheet" />
<script src="libs/dt-core-1.10.20/js/jquery.dataTables.min.js"></script>
<link href="libs/crosstalk-1.1.0.1/css/crosstalk.css" rel="stylesheet" />
<script src="libs/crosstalk-1.1.0.1/js/crosstalk.min.js"></script>


<style type="text/css">
code.sourceCode > span { display: inline-block; line-height: 1.25; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode { white-space: pre; position: relative; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
code.sourceCode { white-space: pre-wrap; }
code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">Data Applications in PA</a></li>

<li class="divider"></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i>Preface</a><ul>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#objective"><i class="fa fa-check"></i>Objective</a></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#style-and-structure"><i class="fa fa-check"></i>Style and Structure</a></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#software-requirements"><i class="fa fa-check"></i>Software requirements</a></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#supplemental-resources"><i class="fa fa-check"></i>Supplemental resources</a></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#r-package-references"><i class="fa fa-check"></i>R Package References</a></li>
</ul></li>
<li class="chapter" data-level="1" data-path="1-intro.html"><a href="1-intro.html"><i class="fa fa-check"></i><b>1</b> Introduction</a><ul>
<li class="chapter" data-level="1.1" data-path="1-intro.html"><a href="1-intro.html#why-statistics"><i class="fa fa-check"></i><b>1.1</b> Why statistics</a></li>
<li class="chapter" data-level="1.2" data-path="1-intro.html"><a href="1-intro.html#professional-standards"><i class="fa fa-check"></i><b>1.2</b> Professional standards</a></li>
<li class="chapter" data-level="1.3" data-path="1-intro.html"><a href="1-intro.html#statistics-in-pa"><i class="fa fa-check"></i><b>1.3</b> Statistics in PA</a></li>
<li class="chapter" data-level="1.4" data-path="1-intro.html"><a href="1-intro.html#using-r"><i class="fa fa-check"></i><b>1.4</b> Using R</a></li>
</ul></li>
<li class="part"><span><b>I Data and Description</b></span></li>
<li class="chapter" data-level="2" data-path="2-data.html"><a href="2-data.html"><i class="fa fa-check"></i><b>2</b> Data</a><ul>
<li class="chapter" data-level="2.1" data-path="2-data.html"><a href="2-data.html#lo2"><i class="fa fa-check"></i><b>2.1</b> Learning objectives</a></li>
<li class="chapter" data-level="2.2" data-path="2-data.html"><a href="2-data.html#rectangular-data"><i class="fa fa-check"></i><b>2.2</b> Rectangular Data</a></li>
<li class="chapter" data-level="2.3" data-path="2-data.html"><a href="2-data.html#types-of-variables"><i class="fa fa-check"></i><b>2.3</b> Types of variables</a><ul>
<li class="chapter" data-level="2.3.1" data-path="2-data.html"><a href="2-data.html#qualitative-variables"><i class="fa fa-check"></i><b>2.3.1</b> Qualitative variables</a></li>
<li class="chapter" data-level="2.3.2" data-path="2-data.html"><a href="2-data.html#quantitative-variables"><i class="fa fa-check"></i><b>2.3.2</b> Quantitative variables</a></li>
<li class="chapter" data-level="2.3.3" data-path="2-data.html"><a href="2-data.html#index-variables"><i class="fa fa-check"></i><b>2.3.3</b> Index variables</a></li>
</ul></li>
<li class="chapter" data-level="2.4" data-path="2-data.html"><a href="2-data.html#dataset-structures"><i class="fa fa-check"></i><b>2.4</b> Dataset structures</a></li>
<li class="chapter" data-level="2.5" data-path="2-data.html"><a href="2-data.html#kt1"><i class="fa fa-check"></i><b>2.5</b> Key terms and concepts</a></li>
</ul></li>
<li class="chapter" data-level="3" data-path="3-measurement-and-missing.html"><a href="3-measurement-and-missing.html"><i class="fa fa-check"></i><b>3</b> Measurement and Missing</a><ul>
<li class="chapter" data-level="3.1" data-path="3-measurement-and-missing.html"><a href="3-measurement-and-missing.html#lo3"><i class="fa fa-check"></i><b>3.1</b> Learning objectives</a></li>
<li class="chapter" data-level="3.2" data-path="3-measurement-and-missing.html"><a href="3-measurement-and-missing.html#credible-analysis"><i class="fa fa-check"></i><b>3.2</b> Credible analysis</a><ul>
<li class="chapter" data-level="3.2.1" data-path="3-measurement-and-missing.html"><a href="3-measurement-and-missing.html#measurement-validity-reliability"><i class="fa fa-check"></i><b>3.2.1</b> Measurement validity &amp; reliability</a></li>
</ul></li>
<li class="chapter" data-level="3.3" data-path="3-measurement-and-missing.html"><a href="3-measurement-and-missing.html#missing-data"><i class="fa fa-check"></i><b>3.3</b> Missing data</a><ul>
<li class="chapter" data-level="3.3.1" data-path="3-measurement-and-missing.html"><a href="3-measurement-and-missing.html#types-of-missing-data"><i class="fa fa-check"></i><b>3.3.1</b> Types of missing data</a></li>
</ul></li>
<li class="chapter" data-level="3.4" data-path="3-measurement-and-missing.html"><a href="3-measurement-and-missing.html#kt2"><i class="fa fa-check"></i><b>3.4</b> Key terms and concepts</a></li>
</ul></li>
<li class="chapter" data-level="4" data-path="4-descriptive-statistics.html"><a href="4-descriptive-statistics.html"><i class="fa fa-check"></i><b>4</b> Descriptive Statistics</a><ul>
<li class="chapter" data-level="4.1" data-path="4-descriptive-statistics.html"><a href="4-descriptive-statistics.html#lo4"><i class="fa fa-check"></i><b>4.1</b> Learning objectives</a></li>
<li class="chapter" data-level="4.2" data-path="4-descriptive-statistics.html"><a href="4-descriptive-statistics.html#two-kinds-of-statistics"><i class="fa fa-check"></i><b>4.2</b> Two kinds of statistics</a></li>
<li class="chapter" data-level="4.3" data-path="4-descriptive-statistics.html"><a href="4-descriptive-statistics.html#distributions"><i class="fa fa-check"></i><b>4.3</b> Distributions</a></li>
<li class="chapter" data-level="4.4" data-path="4-descriptive-statistics.html"><a href="4-descriptive-statistics.html#descriptive-measures"><i class="fa fa-check"></i><b>4.4</b> Descriptive Measures</a><ul>
<li class="chapter" data-level="4.4.1" data-path="4-descriptive-statistics.html"><a href="4-descriptive-statistics.html#measures-of-center"><i class="fa fa-check"></i><b>4.4.1</b> Measures of center</a></li>
<li class="chapter" data-level="4.4.2" data-path="4-descriptive-statistics.html"><a href="4-descriptive-statistics.html#measures-of-spread"><i class="fa fa-check"></i><b>4.4.2</b> Measures of spread</a></li>
<li class="chapter" data-level="4.4.3" data-path="4-descriptive-statistics.html"><a href="4-descriptive-statistics.html#the-normal-distribution"><i class="fa fa-check"></i><b>4.4.3</b> The normal distribution</a></li>
<li class="chapter" data-level="4.4.4" data-path="4-descriptive-statistics.html"><a href="4-descriptive-statistics.html#measures-of-association"><i class="fa fa-check"></i><b>4.4.4</b> Measures of association</a></li>
</ul></li>
<li class="chapter" data-level="4.5" data-path="4-descriptive-statistics.html"><a href="4-descriptive-statistics.html#kt4"><i class="fa fa-check"></i><b>4.5</b> Key terms and concepts</a></li>
</ul></li>
<li class="chapter" data-level="5" data-path="5-data-visualization.html"><a href="5-data-visualization.html"><i class="fa fa-check"></i><b>5</b> Data Visualization</a><ul>
<li class="chapter" data-level="5.1" data-path="5-data-visualization.html"><a href="5-data-visualization.html#lo5"><i class="fa fa-check"></i><b>5.1</b> Learning objectives</a></li>
<li class="chapter" data-level="5.2" data-path="5-data-visualization.html"><a href="5-data-visualization.html#so-many-choices"><i class="fa fa-check"></i><b>5.2</b> So many choices</a></li>
<li class="chapter" data-level="5.3" data-path="5-data-visualization.html"><a href="5-data-visualization.html#distribution"><i class="fa fa-check"></i><b>5.3</b> Distribution</a><ul>
<li class="chapter" data-level="5.3.1" data-path="5-data-visualization.html"><a href="5-data-visualization.html#histogram"><i class="fa fa-check"></i><b>5.3.1</b> Histogram</a></li>
<li class="chapter" data-level="5.3.2" data-path="5-data-visualization.html"><a href="5-data-visualization.html#density"><i class="fa fa-check"></i><b>5.3.2</b> Density</a></li>
<li class="chapter" data-level="5.3.3" data-path="5-data-visualization.html"><a href="5-data-visualization.html#box-plot"><i class="fa fa-check"></i><b>5.3.3</b> Box plot</a></li>
</ul></li>
<li class="chapter" data-level="5.4" data-path="5-data-visualization.html"><a href="5-data-visualization.html#compostion-of-a-category"><i class="fa fa-check"></i><b>5.4</b> Compostion of a category</a><ul>
<li class="chapter" data-level="5.4.1" data-path="5-data-visualization.html"><a href="5-data-visualization.html#pie-charts"><i class="fa fa-check"></i><b>5.4.1</b> Pie charts</a></li>
<li class="chapter" data-level="5.4.2" data-path="5-data-visualization.html"><a href="5-data-visualization.html#bar-chart"><i class="fa fa-check"></i><b>5.4.2</b> Bar chart</a></li>
</ul></li>
<li class="chapter" data-level="5.5" data-path="5-data-visualization.html"><a href="5-data-visualization.html#comparing-between-units"><i class="fa fa-check"></i><b>5.5</b> Comparing between units</a><ul>
<li class="chapter" data-level="5.5.1" data-path="5-data-visualization.html"><a href="5-data-visualization.html#bar-chart-1"><i class="fa fa-check"></i><b>5.5.1</b> Bar chart</a></li>
<li class="chapter" data-level="5.5.2" data-path="5-data-visualization.html"><a href="5-data-visualization.html#dot-plot"><i class="fa fa-check"></i><b>5.5.2</b> Dot plot</a></li>
<li class="chapter" data-level="5.5.3" data-path="5-data-visualization.html"><a href="5-data-visualization.html#line-graph"><i class="fa fa-check"></i><b>5.5.3</b> Line graph</a></li>
</ul></li>
<li class="chapter" data-level="5.6" data-path="5-data-visualization.html"><a href="5-data-visualization.html#association"><i class="fa fa-check"></i><b>5.6</b> Association</a><ul>
<li class="chapter" data-level="5.6.1" data-path="5-data-visualization.html"><a href="5-data-visualization.html#categorical-and-numerical"><i class="fa fa-check"></i><b>5.6.1</b> Categorical and numerical</a></li>
<li class="chapter" data-level="5.6.2" data-path="5-data-visualization.html"><a href="5-data-visualization.html#scatter-plot"><i class="fa fa-check"></i><b>5.6.2</b> Scatter plot</a></li>
</ul></li>
<li class="chapter" data-level="5.7" data-path="5-data-visualization.html"><a href="5-data-visualization.html#kt5"><i class="fa fa-check"></i><b>5.7</b> Key terms and concepts</a></li>
</ul></li>
<li class="part"><span><b>II Regression Models</b></span></li>
<li class="chapter" data-level="6" data-path="6-simple-and-multiple-regression.html"><a href="6-simple-and-multiple-regression.html"><i class="fa fa-check"></i><b>6</b> Simple and Multiple Regression</a><ul>
<li class="chapter" data-level="6.1" data-path="6-simple-and-multiple-regression.html"><a href="6-simple-and-multiple-regression.html#lo6"><i class="fa fa-check"></i><b>6.1</b> Learning objectives</a></li>
<li class="chapter" data-level="6.2" data-path="6-simple-and-multiple-regression.html"><a href="6-simple-and-multiple-regression.html#basic-idea"><i class="fa fa-check"></i><b>6.2</b> Basic idea</a></li>
<li class="chapter" data-level="6.3" data-path="6-simple-and-multiple-regression.html"><a href="6-simple-and-multiple-regression.html#simple-linear-regression"><i class="fa fa-check"></i><b>6.3</b> Simple linear regression</a><ul>
<li class="chapter" data-level="6.3.1" data-path="6-simple-and-multiple-regression.html"><a href="6-simple-and-multiple-regression.html#using-regression"><i class="fa fa-check"></i><b>6.3.1</b> Using regression</a></li>
<li class="chapter" data-level="6.3.2" data-path="6-simple-and-multiple-regression.html"><a href="6-simple-and-multiple-regression.html#the-error-term"><i class="fa fa-check"></i><b>6.3.2</b> The error term</a></li>
<li class="chapter" data-level="6.3.3" data-path="6-simple-and-multiple-regression.html"><a href="6-simple-and-multiple-regression.html#goodness-of-fit"><i class="fa fa-check"></i><b>6.3.3</b> Goodness of fit</a></li>
</ul></li>
<li class="chapter" data-level="6.4" data-path="6-simple-and-multiple-regression.html"><a href="6-simple-and-multiple-regression.html#multiple-regression"><i class="fa fa-check"></i><b>6.4</b> Multiple regression</a><ul>
<li class="chapter" data-level="6.4.1" data-path="6-simple-and-multiple-regression.html"><a href="6-simple-and-multiple-regression.html#using-multiple-regression"><i class="fa fa-check"></i><b>6.4.1</b> Using multiple regression</a></li>
<li class="chapter" data-level="6.4.2" data-path="6-simple-and-multiple-regression.html"><a href="6-simple-and-multiple-regression.html#fit-and-adjusted-r-squared"><i class="fa fa-check"></i><b>6.4.2</b> Fit and adjusted R squared</a></li>
<li class="chapter" data-level="6.4.3" data-path="6-simple-and-multiple-regression.html"><a href="6-simple-and-multiple-regression.html#explanatory-penalty"><i class="fa fa-check"></i><b>6.4.3</b> Explanatory penalty</a></li>
</ul></li>
<li class="chapter" data-level="6.5" data-path="6-simple-and-multiple-regression.html"><a href="6-simple-and-multiple-regression.html#kt6"><i class="fa fa-check"></i><b>6.5</b> Key terms and concepts</a></li>
</ul></li>
<li class="chapter" data-level="7" data-path="7-categorical-variables-and-interactions.html"><a href="7-categorical-variables-and-interactions.html"><i class="fa fa-check"></i><b>7</b> Categorical Variables and Interactions</a><ul>
<li class="chapter" data-level="7.1" data-path="7-categorical-variables-and-interactions.html"><a href="7-categorical-variables-and-interactions.html#lo7"><i class="fa fa-check"></i><b>7.1</b> Learning objectives</a></li>
<li class="chapter" data-level="7.2" data-path="7-categorical-variables-and-interactions.html"><a href="7-categorical-variables-and-interactions.html#parallel-slopes-model"><i class="fa fa-check"></i><b>7.2</b> Parallel slopes model</a><ul>
<li class="chapter" data-level="7.2.1" data-path="7-categorical-variables-and-interactions.html"><a href="7-categorical-variables-and-interactions.html#using-parallel-slopes"><i class="fa fa-check"></i><b>7.2.1</b> Using parallel slopes</a></li>
<li class="chapter" data-level="7.2.2" data-path="7-categorical-variables-and-interactions.html"><a href="7-categorical-variables-and-interactions.html#variations"><i class="fa fa-check"></i><b>7.2.2</b> Variations</a></li>
</ul></li>
<li class="chapter" data-level="7.3" data-path="7-categorical-variables-and-interactions.html"><a href="7-categorical-variables-and-interactions.html#interaction-model"><i class="fa fa-check"></i><b>7.3</b> Interaction model</a><ul>
<li class="chapter" data-level="7.3.1" data-path="7-categorical-variables-and-interactions.html"><a href="7-categorical-variables-and-interactions.html#using-an-interaction"><i class="fa fa-check"></i><b>7.3.1</b> Using an interaction</a></li>
<li class="chapter" data-level="7.3.2" data-path="7-categorical-variables-and-interactions.html"><a href="7-categorical-variables-and-interactions.html#variations-1"><i class="fa fa-check"></i><b>7.3.2</b> Variations</a></li>
</ul></li>
<li class="chapter" data-level="7.4" data-path="7-categorical-variables-and-interactions.html"><a href="7-categorical-variables-and-interactions.html#linear-probability-model"><i class="fa fa-check"></i><b>7.4</b> Linear probability model</a><ul>
<li class="chapter" data-level="7.4.1" data-path="7-categorical-variables-and-interactions.html"><a href="7-categorical-variables-and-interactions.html#using-lpm"><i class="fa fa-check"></i><b>7.4.1</b> Using LPM</a></li>
<li class="chapter" data-level="7.4.2" data-path="7-categorical-variables-and-interactions.html"><a href="7-categorical-variables-and-interactions.html#fit"><i class="fa fa-check"></i><b>7.4.2</b> Fit</a></li>
</ul></li>
<li class="chapter" data-level="7.5" data-path="7-categorical-variables-and-interactions.html"><a href="7-categorical-variables-and-interactions.html#kt7"><i class="fa fa-check"></i><b>7.5</b> Key terms and concepts</a></li>
</ul></li>
<li class="chapter" data-level="8" data-path="8-nonlinear-variables.html"><a href="8-nonlinear-variables.html"><i class="fa fa-check"></i><b>8</b> Nonlinear Variables</a><ul>
<li class="chapter" data-level="8.1" data-path="8-nonlinear-variables.html"><a href="8-nonlinear-variables.html#lo8"><i class="fa fa-check"></i><b>8.1</b> Learning objectives</a></li>
<li class="chapter" data-level="8.2" data-path="8-nonlinear-variables.html"><a href="8-nonlinear-variables.html#quadratic"><i class="fa fa-check"></i><b>8.2</b> Quadratic</a><ul>
<li class="chapter" data-level="8.2.1" data-path="8-nonlinear-variables.html"><a href="8-nonlinear-variables.html#using-quadratics"><i class="fa fa-check"></i><b>8.2.1</b> Using quadratics</a></li>
</ul></li>
<li class="chapter" data-level="8.3" data-path="8-nonlinear-variables.html"><a href="8-nonlinear-variables.html#log-models"><i class="fa fa-check"></i><b>8.3</b> Log models</a><ul>
<li class="chapter" data-level="8.3.1" data-path="8-nonlinear-variables.html"><a href="8-nonlinear-variables.html#logarithmic-scales"><i class="fa fa-check"></i><b>8.3.1</b> Logarithmic scales</a></li>
<li class="chapter" data-level="8.3.2" data-path="8-nonlinear-variables.html"><a href="8-nonlinear-variables.html#percent-v-percentage-point-change"><i class="fa fa-check"></i><b>8.3.2</b> Percent v percentage point change</a></li>
<li class="chapter" data-level="8.3.3" data-path="8-nonlinear-variables.html"><a href="8-nonlinear-variables.html#why-logs-in-regression"><i class="fa fa-check"></i><b>8.3.3</b> Why logs in regression</a></li>
<li class="chapter" data-level="8.3.4" data-path="8-nonlinear-variables.html"><a href="8-nonlinear-variables.html#using-log-models"><i class="fa fa-check"></i><b>8.3.4</b> Using log models</a></li>
</ul></li>
<li class="chapter" data-level="8.4" data-path="8-nonlinear-variables.html"><a href="8-nonlinear-variables.html#kt8"><i class="fa fa-check"></i><b>8.4</b> Key terms and concepts</a></li>
</ul></li>
<li class="chapter" data-level="9" data-path="9-causation-and-bias.html"><a href="9-causation-and-bias.html"><i class="fa fa-check"></i><b>9</b> Causation and Bias</a><ul>
<li class="chapter" data-level="9.1" data-path="9-causation-and-bias.html"><a href="9-causation-and-bias.html#lo9"><i class="fa fa-check"></i><b>9.1</b> Learning objectives</a></li>
<li class="chapter" data-level="9.2" data-path="9-causation-and-bias.html"><a href="9-causation-and-bias.html#causality"><i class="fa fa-check"></i><b>9.2</b> Causality</a></li>
<li class="chapter" data-level="9.3" data-path="9-causation-and-bias.html"><a href="9-causation-and-bias.html#directed-acyclical-graphs"><i class="fa fa-check"></i><b>9.3</b> Directed acyclical graphs</a><ul>
<li class="chapter" data-level="9.3.1" data-path="9-causation-and-bias.html"><a href="9-causation-and-bias.html#evaluationg-dags"><i class="fa fa-check"></i><b>9.3.1</b> Evaluationg DAGs</a></li>
<li class="chapter" data-level="9.3.2" data-path="9-causation-and-bias.html"><a href="9-causation-and-bias.html#backdoor-criterion"><i class="fa fa-check"></i><b>9.3.2</b> Backdoor criterion</a></li>
<li class="chapter" data-level="9.3.3" data-path="9-causation-and-bias.html"><a href="9-causation-and-bias.html#dags-and-regression"><i class="fa fa-check"></i><b>9.3.3</b> DAGs and regression</a></li>
</ul></li>
<li class="chapter" data-level="9.4" data-path="9-causation-and-bias.html"><a href="9-causation-and-bias.html#direction-of-ovb"><i class="fa fa-check"></i><b>9.4</b> Direction of OVB</a></li>
<li class="chapter" data-level="9.5" data-path="9-causation-and-bias.html"><a href="9-causation-and-bias.html#usefulness"><i class="fa fa-check"></i><b>9.5</b> Usefulness</a></li>
<li class="chapter" data-level="9.6" data-path="9-causation-and-bias.html"><a href="9-causation-and-bias.html#kt9"><i class="fa fa-check"></i><b>9.6</b> Key terms and concepts</a></li>
</ul></li>
<li class="part"><span><b>III Inference</b></span></li>
<li class="chapter" data-level="10" data-path="10-sampling.html"><a href="10-sampling.html"><i class="fa fa-check"></i><b>10</b> Sampling</a><ul>
<li class="chapter" data-level="10.1" data-path="10-sampling.html"><a href="10-sampling.html#lo10"><i class="fa fa-check"></i><b>10.1</b> Learning objectives</a></li>
<li class="chapter" data-level="10.2" data-path="10-sampling.html"><a href="10-sampling.html#normal-distribution"><i class="fa fa-check"></i><b>10.2</b> Normal distribution</a></li>
<li class="chapter" data-level="10.3" data-path="10-sampling.html"><a href="10-sampling.html#sampling-distribution"><i class="fa fa-check"></i><b>10.3</b> Sampling Distribution</a></li>
<li class="chapter" data-level="10.4" data-path="10-sampling.html"><a href="10-sampling.html#central-limit-theorem"><i class="fa fa-check"></i><b>10.4</b> Central Limit Theorem</a></li>
<li class="chapter" data-level="10.5" data-path="10-sampling.html"><a href="10-sampling.html#confidence-intervals"><i class="fa fa-check"></i><b>10.5</b> Confidence intervals</a></li>
<li class="chapter" data-level="10.6" data-path="10-sampling.html"><a href="10-sampling.html#conclusion"><i class="fa fa-check"></i><b>10.6</b> Conclusion</a></li>
<li class="chapter" data-level="10.7" data-path="10-sampling.html"><a href="10-sampling.html#kt10"><i class="fa fa-check"></i><b>10.7</b> Key terms and concepts</a></li>
</ul></li>
<li class="chapter" data-level="11" data-path="11-surveys-and-evaluations.html"><a href="11-surveys-and-evaluations.html"><i class="fa fa-check"></i><b>11</b> Surveys and Evaluations</a><ul>
<li class="chapter" data-level="11.1" data-path="11-surveys-and-evaluations.html"><a href="11-surveys-and-evaluations.html#lo11"><i class="fa fa-check"></i><b>11.1</b> Learning objectives</a></li>
<li class="chapter" data-level="11.2" data-path="11-surveys-and-evaluations.html"><a href="11-surveys-and-evaluations.html#sample-size"><i class="fa fa-check"></i><b>11.2</b> Sample size</a></li>
<li class="chapter" data-level="11.3" data-path="11-surveys-and-evaluations.html"><a href="11-surveys-and-evaluations.html#survey-weights"><i class="fa fa-check"></i><b>11.3</b> Survey weights</a></li>
<li class="chapter" data-level="11.4" data-path="11-surveys-and-evaluations.html"><a href="11-surveys-and-evaluations.html#hypothesis-testing"><i class="fa fa-check"></i><b>11.4</b> Hypothesis testing</a><ul>
<li class="chapter" data-level="11.4.1" data-path="11-surveys-and-evaluations.html"><a href="11-surveys-and-evaluations.html#null-and-alternative-hypos"><i class="fa fa-check"></i><b>11.4.1</b> Null and alternative hypos</a></li>
<li class="chapter" data-level="11.4.2" data-path="11-surveys-and-evaluations.html"><a href="11-surveys-and-evaluations.html#conclusion-and-error-type"><i class="fa fa-check"></i><b>11.4.2</b> Conclusion and error type</a></li>
<li class="chapter" data-level="11.4.3" data-path="11-surveys-and-evaluations.html"><a href="11-surveys-and-evaluations.html#decision-rule"><i class="fa fa-check"></i><b>11.4.3</b> Decision rule</a></li>
</ul></li>
<li class="chapter" data-level="11.5" data-path="11-surveys-and-evaluations.html"><a href="11-surveys-and-evaluations.html#chi-square-test"><i class="fa fa-check"></i><b>11.5</b> Chi-square test</a></li>
<li class="chapter" data-level="11.6" data-path="11-surveys-and-evaluations.html"><a href="11-surveys-and-evaluations.html#t-test"><i class="fa fa-check"></i><b>11.6</b> T-test</a></li>
<li class="chapter" data-level="11.7" data-path="11-surveys-and-evaluations.html"><a href="11-surveys-and-evaluations.html#kt11"><i class="fa fa-check"></i><b>11.7</b> Key terms and concepts</a></li>
</ul></li>
<li class="chapter" data-level="12" data-path="12-regression-inference.html"><a href="12-regression-inference.html"><i class="fa fa-check"></i><b>12</b> Regression Inference</a><ul>
<li class="chapter" data-level="12.1" data-path="12-regression-inference.html"><a href="12-regression-inference.html#lo12"><i class="fa fa-check"></i><b>12.1</b> Learning objectives</a></li>
<li class="chapter" data-level="12.2" data-path="12-regression-inference.html"><a href="12-regression-inference.html#regression-table"><i class="fa fa-check"></i><b>12.2</b> Regression table</a></li>
<li class="chapter" data-level="12.3" data-path="12-regression-inference.html"><a href="12-regression-inference.html#other-hypotheses"><i class="fa fa-check"></i><b>12.3</b> Other hypotheses</a></li>
<li class="chapter" data-level="12.4" data-path="12-regression-inference.html"><a href="12-regression-inference.html#practical-significance"><i class="fa fa-check"></i><b>12.4</b> Practical significance</a></li>
<li class="chapter" data-level="12.5" data-path="12-regression-inference.html"><a href="12-regression-inference.html#kt12"><i class="fa fa-check"></i><b>12.5</b> Key terms and concepts</a></li>
</ul></li>
<li class="chapter" data-level="13" data-path="13-regression-diagnostics.html"><a href="13-regression-diagnostics.html"><i class="fa fa-check"></i><b>13</b> Regression Diagnostics</a><ul>
<li class="chapter" data-level="13.1" data-path="13-regression-diagnostics.html"><a href="13-regression-diagnostics.html#lo13"><i class="fa fa-check"></i><b>13.1</b> Learning objectives</a></li>
<li class="chapter" data-level="13.2" data-path="13-regression-diagnostics.html"><a href="13-regression-diagnostics.html#classical-assumptions"><i class="fa fa-check"></i><b>13.2</b> Classical assumptions</a></li>
<li class="chapter" data-level="13.3" data-path="13-regression-diagnostics.html"><a href="13-regression-diagnostics.html#multicollinearity"><i class="fa fa-check"></i><b>13.3</b> Multicollinearity</a></li>
<li class="chapter" data-level="13.4" data-path="13-regression-diagnostics.html"><a href="13-regression-diagnostics.html#influential-data"><i class="fa fa-check"></i><b>13.4</b> Influential Data</a></li>
<li class="chapter" data-level="13.5" data-path="13-regression-diagnostics.html"><a href="13-regression-diagnostics.html#kt13"><i class="fa fa-check"></i><b>13.5</b> Key terms and concepts</a></li>
</ul></li>
<li class="part"><span><b>IV Advanced Topics</b></span></li>
<li class="chapter" data-level="14" data-path="14-forecasting.html"><a href="14-forecasting.html"><i class="fa fa-check"></i><b>14</b> Forecasting</a><ul>
<li class="chapter" data-level="14.1" data-path="14-forecasting.html"><a href="14-forecasting.html#what-is-forecasting"><i class="fa fa-check"></i><b>14.1</b> What is forecasting</a></li>
<li class="chapter" data-level="14.2" data-path="14-forecasting.html"><a href="14-forecasting.html#patterns"><i class="fa fa-check"></i><b>14.2</b> Patterns</a><ul>
<li class="chapter" data-level="14.2.1" data-path="14-forecasting.html"><a href="14-forecasting.html#autocorrelation"><i class="fa fa-check"></i><b>14.2.1</b> Autocorrelation</a></li>
</ul></li>
<li class="chapter" data-level="14.3" data-path="14-forecasting.html"><a href="14-forecasting.html#forecasting-basics"><i class="fa fa-check"></i><b>14.3</b> Forecasting basics</a><ul>
<li class="chapter" data-level="14.3.1" data-path="14-forecasting.html"><a href="14-forecasting.html#evaluation"><i class="fa fa-check"></i><b>14.3.1</b> Evaluation</a></li>
<li class="chapter" data-level="14.3.2" data-path="14-forecasting.html"><a href="14-forecasting.html#models"><i class="fa fa-check"></i><b>14.3.2</b> Models</a></li>
</ul></li>
<li class="chapter" data-level="14.4" data-path="14-forecasting.html"><a href="14-forecasting.html#recap"><i class="fa fa-check"></i><b>14.4</b> Recap</a></li>
</ul></li>
<li class="chapter" data-level="15" data-path="15-panel-analysis.html"><a href="15-panel-analysis.html"><i class="fa fa-check"></i><b>15</b> Panel Analysis</a><ul>
<li class="chapter" data-level="15.1" data-path="15-panel-analysis.html"><a href="15-panel-analysis.html#panel-data"><i class="fa fa-check"></i><b>15.1</b> Panel data</a></li>
<li class="chapter" data-level="15.2" data-path="15-panel-analysis.html"><a href="15-panel-analysis.html#fixed-effects"><i class="fa fa-check"></i><b>15.2</b> Fixed effects</a></li>
</ul></li>
<li class="part"><span><b>V R Chapters</b></span></li>
<li class="chapter" data-level="16" data-path="16-r-introduction.html"><a href="16-r-introduction.html"><i class="fa fa-check"></i><b>16</b> R Introduction</a><ul>
<li class="chapter" data-level="16.1" data-path="16-r-introduction.html"><a href="16-r-introduction.html#r-chapter-structure"><i class="fa fa-check"></i><b>16.1</b> R chapter structure</a></li>
<li class="chapter" data-level="16.2" data-path="16-r-introduction.html"><a href="16-r-introduction.html#r-chapter-feedback"><i class="fa fa-check"></i><b>16.2</b> R chapter feedback</a></li>
<li class="chapter" data-level="16.3" data-path="16-r-introduction.html"><a href="16-r-introduction.html#what-is-r-and-rstudio"><i class="fa fa-check"></i><b>16.3</b> What is R and RStudio</a></li>
<li class="chapter" data-level="16.4" data-path="16-r-introduction.html"><a href="16-r-introduction.html#installing-r-and-rstudio"><i class="fa fa-check"></i><b>16.4</b> Installing R and RStudio</a></li>
<li class="chapter" data-level="16.5" data-path="16-r-introduction.html"><a href="16-r-introduction.html#rstudio-orientation"><i class="fa fa-check"></i><b>16.5</b> RStudio orientation</a><ul>
<li class="chapter" data-level="16.5.1" data-path="16-r-introduction.html"><a href="16-r-introduction.html#r-packages"><i class="fa fa-check"></i><b>16.5.1</b> R Packages</a></li>
</ul></li>
<li class="chapter" data-level="16.6" data-path="16-r-introduction.html"><a href="16-r-introduction.html#submit"><i class="fa fa-check"></i><b>16.6</b> Submit</a></li>
<li class="chapter" data-level="16.7" data-path="16-r-introduction.html"><a href="16-r-introduction.html#additional-resources"><i class="fa fa-check"></i><b>16.7</b> Additional Resources</a></li>
</ul></li>
<li class="chapter" data-level="17" data-path="17-r-data.html"><a href="17-r-data.html"><i class="fa fa-check"></i><b>17</b> R Data</a><ul>
<li class="chapter" data-level="17.1" data-path="17-r-data.html"><a href="17-r-data.html#learning-objectives"><i class="fa fa-check"></i><b>17.1</b> Learning Objectives</a></li>
<li class="chapter" data-level="17.2" data-path="17-r-data.html"><a href="17-r-data.html#set-up"><i class="fa fa-check"></i><b>17.2</b> Set-up</a></li>
<li class="chapter" data-level="17.3" data-path="17-r-data.html"><a href="17-r-data.html#viewing-datasets"><i class="fa fa-check"></i><b>17.3</b> Viewing datasets</a><ul>
<li class="chapter" data-level="17.3.1" data-path="17-r-data.html"><a href="17-r-data.html#warning-about-view"><i class="fa fa-check"></i><b>17.3.1</b> Warning about View</a></li>
</ul></li>
<li class="chapter" data-level="17.4" data-path="17-r-data.html"><a href="17-r-data.html#glimpsing-datasets"><i class="fa fa-check"></i><b>17.4</b> Glimpsing Datasets</a></li>
<li class="chapter" data-level="17.5" data-path="17-r-data.html"><a href="17-r-data.html#preview-first-or-last-few-rows"><i class="fa fa-check"></i><b>17.5</b> Preview first or last few rows</a></li>
<li class="chapter" data-level="17.6" data-path="16-r-introduction.html"><a href="16-r-introduction.html#submit"><i class="fa fa-check"></i><b>17.6</b> Submit</a></li>
</ul></li>
<li class="chapter" data-level="18" data-path="18-r-missing-data.html"><a href="18-r-missing-data.html"><i class="fa fa-check"></i><b>18</b> R Missing Data</a><ul>
<li class="chapter" data-level="18.1" data-path="17-r-data.html"><a href="17-r-data.html#learning-objectives"><i class="fa fa-check"></i><b>18.1</b> Learning Objectives</a></li>
<li class="chapter" data-level="18.2" data-path="17-r-data.html"><a href="17-r-data.html#set-up"><i class="fa fa-check"></i><b>18.2</b> Set-up</a></li>
<li class="chapter" data-level="18.3" data-path="2-data.html"><a href="2-data.html#data"><i class="fa fa-check"></i><b>18.3</b> Data</a></li>
<li class="chapter" data-level="18.4" data-path="18-r-missing-data.html"><a href="18-r-missing-data.html#checking-for-missing-data"><i class="fa fa-check"></i><b>18.4</b> Checking for missing data</a></li>
<li class="chapter" data-level="18.5" data-path="18-r-missing-data.html"><a href="18-r-missing-data.html#counting-missing-values"><i class="fa fa-check"></i><b>18.5</b> Counting missing values</a></li>
<li class="chapter" data-level="18.6" data-path="18-r-missing-data.html"><a href="18-r-missing-data.html#bypassing-missing-values"><i class="fa fa-check"></i><b>18.6</b> Bypassing missing values</a></li>
<li class="chapter" data-level="18.7" data-path="18-r-missing-data.html"><a href="18-r-missing-data.html#replacing-missing-values"><i class="fa fa-check"></i><b>18.7</b> Replacing missing values</a></li>
<li class="chapter" data-level="18.8" data-path="16-r-introduction.html"><a href="16-r-introduction.html#submit"><i class="fa fa-check"></i><b>18.8</b> Submit</a></li>
</ul></li>
<li class="chapter" data-level="19" data-path="19-r-description.html"><a href="19-r-description.html"><i class="fa fa-check"></i><b>19</b> R Description</a><ul>
<li class="chapter" data-level="19.1" data-path="17-r-data.html"><a href="17-r-data.html#learning-objectives"><i class="fa fa-check"></i><b>19.1</b> Learning Objectives</a></li>
<li class="chapter" data-level="19.2" data-path="17-r-data.html"><a href="17-r-data.html#set-up"><i class="fa fa-check"></i><b>19.2</b> Set-up</a></li>
<li class="chapter" data-level="19.3" data-path="19-r-description.html"><a href="19-r-description.html#introduction"><i class="fa fa-check"></i><b>19.3</b> Introduction</a></li>
<li class="chapter" data-level="19.4" data-path="19-r-description.html"><a href="19-r-description.html#summary-table"><i class="fa fa-check"></i><b>19.4</b> Summary Table</a></li>
<li class="chapter" data-level="19.5" data-path="19-r-description.html"><a href="19-r-description.html#using-arsenal"><i class="fa fa-check"></i><b>19.5</b> Using Arsenal</a><ul>
<li class="chapter" data-level="19.5.1" data-path="19-r-description.html"><a href="19-r-description.html#adjustments"><i class="fa fa-check"></i><b>19.5.1</b> Adjustments</a></li>
<li class="chapter" data-level="19.5.2" data-path="19-r-description.html"><a href="19-r-description.html#export-to-csv"><i class="fa fa-check"></i><b>19.5.2</b> Export to CSV</a></li>
</ul></li>
<li class="chapter" data-level="19.6" data-path="16-r-introduction.html"><a href="16-r-introduction.html#submit"><i class="fa fa-check"></i><b>19.6</b> Submit</a></li>
</ul></li>
<li class="chapter" data-level="20" data-path="20-r-visualization.html"><a href="20-r-visualization.html"><i class="fa fa-check"></i><b>20</b> R Visualization</a><ul>
<li class="chapter" data-level="20.1" data-path="17-r-data.html"><a href="17-r-data.html#learning-objectives"><i class="fa fa-check"></i><b>20.1</b> Learning Objectives</a></li>
<li class="chapter" data-level="20.2" data-path="17-r-data.html"><a href="17-r-data.html#set-up"><i class="fa fa-check"></i><b>20.2</b> Set-up</a></li>
<li class="chapter" data-level="20.3" data-path="20-r-visualization.html"><a href="20-r-visualization.html#grammar-of-graphics"><i class="fa fa-check"></i><b>20.3</b> Grammar of graphics</a></li>
<li class="chapter" data-level="20.4" data-path="5-data-visualization.html"><a href="5-data-visualization.html#histogram"><i class="fa fa-check"></i><b>20.4</b> Histogram</a></li>
<li class="chapter" data-level="20.5" data-path="5-data-visualization.html"><a href="5-data-visualization.html#box-plot"><i class="fa fa-check"></i><b>20.5</b> Box plot</a></li>
<li class="chapter" data-level="20.6" data-path="5-data-visualization.html"><a href="5-data-visualization.html#bar-chart"><i class="fa fa-check"></i><b>20.6</b> Bar chart</a></li>
<li class="chapter" data-level="20.7" data-path="5-data-visualization.html"><a href="5-data-visualization.html#scatter-plot"><i class="fa fa-check"></i><b>20.7</b> Scatter plot</a></li>
<li class="chapter" data-level="20.8" data-path="5-data-visualization.html"><a href="5-data-visualization.html#line-graph"><i class="fa fa-check"></i><b>20.8</b> Line graph</a></li>
<li class="chapter" data-level="20.9" data-path="16-r-introduction.html"><a href="16-r-introduction.html#submit"><i class="fa fa-check"></i><b>20.9</b> Submit</a></li>
</ul></li>
<li class="chapter" data-level="21" data-path="21-r-regression.html"><a href="21-r-regression.html"><i class="fa fa-check"></i><b>21</b> R Regression</a><ul>
<li class="chapter" data-level="21.1" data-path="17-r-data.html"><a href="17-r-data.html#learning-objectives"><i class="fa fa-check"></i><b>21.1</b> Learning Objectives</a></li>
<li class="chapter" data-level="21.2" data-path="17-r-data.html"><a href="17-r-data.html#set-up"><i class="fa fa-check"></i><b>21.2</b> Set-up</a></li>
<li class="chapter" data-level="21.3" data-path="21-r-regression.html"><a href="21-r-regression.html#running-regression"><i class="fa fa-check"></i><b>21.3</b> Running Regression</a></li>
<li class="chapter" data-level="21.4" data-path="21-r-regression.html"><a href="21-r-regression.html#reporting-results"><i class="fa fa-check"></i><b>21.4</b> Reporting Results</a><ul>
<li class="chapter" data-level="21.4.1" data-path="21-r-regression.html"><a href="21-r-regression.html#moderndive"><i class="fa fa-check"></i><b>21.4.1</b> Moderndive</a></li>
<li class="chapter" data-level="21.4.2" data-path="21-r-regression.html"><a href="21-r-regression.html#base-r"><i class="fa fa-check"></i><b>21.4.2</b> Base R</a></li>
</ul></li>
<li class="chapter" data-level="21.5" data-path="16-r-introduction.html"><a href="16-r-introduction.html#submit"><i class="fa fa-check"></i><b>21.5</b> Submit</a></li>
</ul></li>
<li class="chapter" data-level="22" data-path="22-r-interactions.html"><a href="22-r-interactions.html"><i class="fa fa-check"></i><b>22</b> R Interactions</a><ul>
<li class="chapter" data-level="22.1" data-path="17-r-data.html"><a href="17-r-data.html#learning-objectives"><i class="fa fa-check"></i><b>22.1</b> Learning Objectives</a></li>
<li class="chapter" data-level="22.2" data-path="17-r-data.html"><a href="17-r-data.html#set-up"><i class="fa fa-check"></i><b>22.2</b> Set-up</a></li>
<li class="chapter" data-level="22.3" data-path="22-r-interactions.html"><a href="22-r-interactions.html#including-an-interaction"><i class="fa fa-check"></i><b>22.3</b> Including an interaction</a></li>
<li class="chapter" data-level="22.4" data-path="16-r-introduction.html"><a href="16-r-introduction.html#submit"><i class="fa fa-check"></i><b>22.4</b> Submit</a></li>
</ul></li>
<li class="chapter" data-level="23" data-path="23-r-nonlinear-regression.html"><a href="23-r-nonlinear-regression.html"><i class="fa fa-check"></i><b>23</b> R Nonlinear Regression</a><ul>
<li class="chapter" data-level="23.1" data-path="17-r-data.html"><a href="17-r-data.html#learning-objectives"><i class="fa fa-check"></i><b>23.1</b> Learning Objectives</a></li>
<li class="chapter" data-level="23.2" data-path="17-r-data.html"><a href="17-r-data.html#set-up"><i class="fa fa-check"></i><b>23.2</b> Set-up</a></li>
<li class="chapter" data-level="23.3" data-path="23-r-nonlinear-regression.html"><a href="23-r-nonlinear-regression.html#quadratic-term"><i class="fa fa-check"></i><b>23.3</b> Quadratic term</a></li>
<li class="chapter" data-level="23.4" data-path="23-r-nonlinear-regression.html"><a href="23-r-nonlinear-regression.html#log-transformation"><i class="fa fa-check"></i><b>23.4</b> Log Transformation</a></li>
<li class="chapter" data-level="23.5" data-path="16-r-introduction.html"><a href="16-r-introduction.html#submit"><i class="fa fa-check"></i><b>23.5</b> Submit</a></li>
</ul></li>
<li class="chapter" data-level="24" data-path="24-r-evaluations.html"><a href="24-r-evaluations.html"><i class="fa fa-check"></i><b>24</b> R Evaluations</a><ul>
<li class="chapter" data-level="24.1" data-path="24-r-evaluations.html"><a href="24-r-evaluations.html#learning-outcomes"><i class="fa fa-check"></i><b>24.1</b> Learning Outcomes</a></li>
<li class="chapter" data-level="24.2" data-path="17-r-data.html"><a href="17-r-data.html#set-up"><i class="fa fa-check"></i><b>24.2</b> Set-up</a></li>
<li class="chapter" data-level="24.3" data-path="11-surveys-and-evaluations.html"><a href="11-surveys-and-evaluations.html#chi-square-test"><i class="fa fa-check"></i><b>24.3</b> Chi-square test</a><ul>
<li class="chapter" data-level="24.3.1" data-path="24-r-evaluations.html"><a href="24-r-evaluations.html#cross-tab"><i class="fa fa-check"></i><b>24.3.1</b> Cross-tab</a></li>
<li class="chapter" data-level="24.3.2" data-path="24-r-evaluations.html"><a href="24-r-evaluations.html#run-chi-square"><i class="fa fa-check"></i><b>24.3.2</b> Run chi-square</a></li>
</ul></li>
<li class="chapter" data-level="24.4" data-path="24-r-evaluations.html"><a href="24-r-evaluations.html#t-tests"><i class="fa fa-check"></i><b>24.4</b> T-tests</a><ul>
<li class="chapter" data-level="24.4.1" data-path="24-r-evaluations.html"><a href="24-r-evaluations.html#independent-t-test"><i class="fa fa-check"></i><b>24.4.1</b> Independent t-test</a></li>
<li class="chapter" data-level="24.4.2" data-path="24-r-evaluations.html"><a href="24-r-evaluations.html#dependent-t-test"><i class="fa fa-check"></i><b>24.4.2</b> Dependent t-test</a></li>
</ul></li>
<li class="chapter" data-level="24.5" data-path="16-r-introduction.html"><a href="16-r-introduction.html#submit"><i class="fa fa-check"></i><b>24.5</b> Submit</a></li>
</ul></li>
<li class="chapter" data-level="25" data-path="25-r-regression-diagnostics.html"><a href="25-r-regression-diagnostics.html"><i class="fa fa-check"></i><b>25</b> R Regression Diagnostics</a><ul>
<li class="chapter" data-level="25.1" data-path="24-r-evaluations.html"><a href="24-r-evaluations.html#learning-outcomes"><i class="fa fa-check"></i><b>25.1</b> Learning Outcomes</a></li>
<li class="chapter" data-level="25.2" data-path="17-r-data.html"><a href="17-r-data.html#set-up"><i class="fa fa-check"></i><b>25.2</b> Set-up</a></li>
<li class="chapter" data-level="25.3" data-path="25-r-regression-diagnostics.html"><a href="25-r-regression-diagnostics.html#diagnostic-plots"><i class="fa fa-check"></i><b>25.3</b> Diagnostic Plots</a></li>
<li class="chapter" data-level="25.4" data-path="25-r-regression-diagnostics.html"><a href="25-r-regression-diagnostics.html#variance-inflation-factor"><i class="fa fa-check"></i><b>25.4</b> Variance Inflation Factor</a></li>
<li class="chapter" data-level="25.5" data-path="25-r-regression-diagnostics.html"><a href="25-r-regression-diagnostics.html#statistical-test-on-assumption"><i class="fa fa-check"></i><b>25.5</b> Statistical test on assumption</a></li>
<li class="chapter" data-level="25.6" data-path="25-r-regression-diagnostics.html"><a href="25-r-regression-diagnostics.html#excluding-observations"><i class="fa fa-check"></i><b>25.6</b> Excluding observations</a></li>
<li class="chapter" data-level="25.7" data-path="16-r-introduction.html"><a href="16-r-introduction.html#submit"><i class="fa fa-check"></i><b>25.7</b> Submit</a></li>
</ul></li>
<li class="appendix"><span><b>Appendix</b></span></li>
<li class="chapter" data-level="A" data-path="A-wrangle-and-tidy-reference.html"><a href="A-wrangle-and-tidy-reference.html"><i class="fa fa-check"></i><b>A</b> Wrangle and Tidy Reference</a><ul>
<li class="chapter" data-level="A.1" data-path="A-wrangle-and-tidy-reference.html"><a href="A-wrangle-and-tidy-reference.html#cheatsheets"><i class="fa fa-check"></i><b>A.1</b> Cheatsheets</a></li>
<li class="chapter" data-level="A.2" data-path="A-wrangle-and-tidy-reference.html"><a href="A-wrangle-and-tidy-reference.html#wrangle-verbs"><i class="fa fa-check"></i><b>A.2</b> Wrangle Verbs</a><ul>
<li class="chapter" data-level="" data-path="A-wrangle-and-tidy-reference.html"><a href="A-wrangle-and-tidy-reference.html#filter"><i class="fa fa-check"></i>Filter</a></li>
<li class="chapter" data-level="" data-path="A-wrangle-and-tidy-reference.html"><a href="A-wrangle-and-tidy-reference.html#select"><i class="fa fa-check"></i>Select</a></li>
<li class="chapter" data-level="" data-path="A-wrangle-and-tidy-reference.html"><a href="A-wrangle-and-tidy-reference.html#mutate"><i class="fa fa-check"></i>Mutate</a></li>
<li class="chapter" data-level="" data-path="A-wrangle-and-tidy-reference.html"><a href="A-wrangle-and-tidy-reference.html#combining-filter-select-and-mutate"><i class="fa fa-check"></i>Combining filter, select, and mutate</a></li>
<li class="chapter" data-level="" data-path="A-wrangle-and-tidy-reference.html"><a href="A-wrangle-and-tidy-reference.html#arrange"><i class="fa fa-check"></i>Arrange</a></li>
<li class="chapter" data-level="" data-path="A-wrangle-and-tidy-reference.html"><a href="A-wrangle-and-tidy-reference.html#headtail"><i class="fa fa-check"></i>Head/Tail</a></li>
<li class="chapter" data-level="" data-path="A-wrangle-and-tidy-reference.html"><a href="A-wrangle-and-tidy-reference.html#summarize"><i class="fa fa-check"></i>Summarize</a></li>
<li class="chapter" data-level="" data-path="A-wrangle-and-tidy-reference.html"><a href="A-wrangle-and-tidy-reference.html#group_by"><i class="fa fa-check"></i>Group_By</a></li>
</ul></li>
<li class="chapter" data-level="A.3" data-path="A-wrangle-and-tidy-reference.html"><a href="A-wrangle-and-tidy-reference.html#tidy-verbs"><i class="fa fa-check"></i><b>A.3</b> Tidy Verbs</a></li>
</ul></li>
<li class="divider"></li>
<li><a href="https://github.com/rstudio/bookdown" target="blank">Published with bookdown</a></li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Data Applications in Public Administration</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="nonlinear-variables" class="section level1">
<h1><span class="header-section-number"> 8</span> Nonlinear Variables</h1>
<blockquote>
<p><em>“The shortest distance between two points is often unbearable.”</em></p>
<p>—Charles Bukowski</p>
</blockquote>
<p>So far, we have repeatedly drawn straight lines through points. But, we know not all relationships are linear. Our income tends to rise and fall with age. Those in charge of the purchasing or production of something should know that average and marginal costs fall and then rise with quantity. Happiness tends to rise sharply with income but then plateaus at around $70,000 per year. If our goal is to draw the line that fits data best, why draw a straight line through data that is evidently nonlinear?</p>
<p>In this chapter, we will cover two ways to incorporate nonlinear relationships:</p>
<ul>
<li>Include a quadratic</li>
<li>Include a logarithmic transformation</li>
</ul>
<div id="lo8" class="section level2">
<h2><span class="header-section-number">8.1</span> Learning objectives</h2>
<div class="learncheck">
<ul>
<li>
Explain why and how to extend a regression model to include a quadratic relationship
</li>
<li>
Interpret the coefficients associated with a quadratic term in a regression model
</li>
<li>
Compute the value of the quadratic explanatory variable at which the outcome is at its maximum or minimum
</li>
<li>
Explain the difference between percent change and percentage point change
</li>
<li>
Explain why to log-transform variables in a regression model
</li>
<li>
Interpret results from log-log, log-level, and level-log models
</li>
</ul>
</div>
</div>
<div id="quadratic" class="section level2">
<h2><span class="header-section-number">8.2</span> Quadratic</h2>
<p>If we theorize or see visual evidence that the association between an explanatory variable and an outcome is such that the outcome initially increases or decreases as the explanatory variable increases, then, at some value of the explanatory variable, the outcome decreases, then we may want to include a quadratic term of that explanatory variable in our regression model. That long-winded statement warrants an immediate visualization provided by Figure <a href="8-nonlinear-variables.html#fig:quadscatter">8.1</a> below.</p>
<p>Note that wage appears to initially increase with age, then decreases. The data present a pattern that resembles an inverted U, also known as a concave parabola. Age and wage is a classic example of a quadratic relationship. We should not force ourselves to fit a straight line to these data; we can estimate a better line.</p>
<div class="figure"><span id="fig:quadscatter"></span>
<img src="data-apps-text_files/figure-html/quadscatter-1.png" alt="Wages by age" width="672" />
<p class="caption">
Figure 8.1: Wages by age
</p>
</div>
<p>Equation <a href="8-nonlinear-variables.html#eq:quadratic">(8.1)</a> presents a generic population regression model with a quadratic term. With respect to the math, the only difference between this and previous models is the choice to square one of the explanatory variables. This is just an example. Any number of explanatory variables can be squared if theory warrants it.</p>
<p><span class="math display" id="eq:quadratic">\[\begin{equation}
y = \beta_0 + \beta_1x_1 + \beta_2x_1^2 + \beta_3x_2 + \cdots + \beta_kx_k + \epsilon
\tag{8.1}
\end{equation}\]</span></p>
<p>Thus, the sample equation is as follows</p>
<p><span class="math display" id="eq:quadraticsamp">\[\begin{equation}
\hat{y} = b_0 + b_1x_1 + b_2x_1^2 + b_3x_2 + \cdots + b_kx_k
\tag{8.2}
\end{equation}\]</span></p>
<p>Fully understanding the logic of the above equations to answer questions we may encounter as we have done before involves calculus that this book will spare you. In order to report the marginal effect of a variable that has been squared on an outcome in regression, we use Equation <a href="8-nonlinear-variables.html#eq:quadraticsampmarg">(8.3)</a> below. The result of this equation provides the predicted change in <span class="math inline">\(y\)</span> given a one-unit change in <span class="math inline">\(x_1\)</span>.</p>
<p><span class="math display" id="eq:quadraticsampmarg">\[\begin{equation}
b_1 + 2b_2x_1
\tag{8.3}
\end{equation}\]</span></p>
<p>Note that had we not squared <span class="math inline">\(x_1\)</span> the predicted change in <span class="math inline">\(y\)</span> from a one-unit change in <span class="math inline">\(x_1\)</span> would be <span class="math inline">\(b_1\)</span>, which is exactly the same as in previous models. However, now that we are drawing a curved line, the effect of a one-unit change in <span class="math inline">\(x\)</span> on <span class="math inline">\(y\)</span> is not constant; it changes depending on the value of <span class="math inline">\(x\)</span>.</p>
<p>Another important question when a quadratic relationship is involved is at what value of <span class="math inline">\(x\)</span> is <span class="math inline">\(y\)</span> maximized or minimized. This can help decision-making, such as how to minimize costs or maximize profit, or maximize the probability of some desirable outcome. In order to report the value of <span class="math inline">\(x\)</span> at which <span class="math inline">\(y\)</span> reaches its maximum or minimum, we use Equation <a href="8-nonlinear-variables.html#eq:quadraticsampopt">(8.4)</a> below. The result of the equation gives us the optimal value of <span class="math inline">\(x\)</span>.</p>
<p><span class="math display" id="eq:quadraticsampopt">\[\begin{equation}
x = {\frac{-b_1}{2b_2}}
\tag{8.4}
\end{equation}\]</span></p>
<div id="using-quadratics" class="section level3">
<h3><span class="header-section-number">8.2.1</span> Using quadratics</h3>
<p>Suppose we collect the following data.</p>
<table>
<caption>
<span id="tab:wagestab">Table 8.1: </span>Preview of wages, age, and education
</caption>
<thead>
<tr>
<th style="text-align:right;">
Wage
</th>
<th style="text-align:right;">
Educ
</th>
<th style="text-align:right;">
Age
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:right;">
19.13
</td>
<td style="text-align:right;">
9
</td>
<td style="text-align:right;">
35
</td>
</tr>
<tr>
<td style="text-align:right;">
25.67
</td>
<td style="text-align:right;">
12
</td>
<td style="text-align:right;">
37
</td>
</tr>
<tr>
<td style="text-align:right;">
38.77
</td>
<td style="text-align:right;">
21
</td>
<td style="text-align:right;">
41
</td>
</tr>
<tr>
<td style="text-align:right;">
32.37
</td>
<td style="text-align:right;">
17
</td>
<td style="text-align:right;">
53
</td>
</tr>
<tr>
<td style="text-align:right;">
19.34
</td>
<td style="text-align:right;">
6
</td>
<td style="text-align:right;">
38
</td>
</tr>
<tr>
<td style="text-align:right;">
18.76
</td>
<td style="text-align:right;">
18
</td>
<td style="text-align:right;">
73
</td>
</tr>
<tr>
<td style="text-align:right;">
18.11
</td>
<td style="text-align:right;">
14
</td>
<td style="text-align:right;">
21
</td>
</tr>
</tbody>
</table>
<p>Therefore, our regression equation is as follows</p>
<p><span class="math display" id="eq:quadraticex">\[\begin{equation}
Wage = \beta_0 + \beta_1Age + \beta_2Age^2 + \beta_3Educ + \epsilon
\tag{8.5}
\end{equation}\]</span></p>
<p>Running this regression generates the following results</p>
<table>
<caption>
<span id="tab:quadextab">Table 8.2: </span>Quadratic model results
</caption>
<thead>
<tr>
<th style="text-align:left;">
term
</th>
<th style="text-align:right;">
estimate
</th>
<th style="text-align:right;">
std_error
</th>
<th style="text-align:right;">
statistic
</th>
<th style="text-align:right;">
p_value
</th>
<th style="text-align:right;">
lower_ci
</th>
<th style="text-align:right;">
upper_ci
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;">
intercept
</td>
<td style="text-align:right;">
-22.722
</td>
<td style="text-align:right;">
3.023
</td>
<td style="text-align:right;">
-7.517
</td>
<td style="text-align:right;">
0
</td>
<td style="text-align:right;">
-28.742
</td>
<td style="text-align:right;">
-16.701
</td>
</tr>
<tr>
<td style="text-align:left;">
Age
</td>
<td style="text-align:right;">
1.350
</td>
<td style="text-align:right;">
0.134
</td>
<td style="text-align:right;">
10.077
</td>
<td style="text-align:right;">
0
</td>
<td style="text-align:right;">
1.083
</td>
<td style="text-align:right;">
1.617
</td>
</tr>
<tr>
<td style="text-align:left;">
I(Age^2)
</td>
<td style="text-align:right;">
-0.013
</td>
<td style="text-align:right;">
0.001
</td>
<td style="text-align:right;">
-9.840
</td>
<td style="text-align:right;">
0
</td>
<td style="text-align:right;">
-0.016
</td>
<td style="text-align:right;">
-0.011
</td>
</tr>
<tr>
<td style="text-align:left;">
Educ
</td>
<td style="text-align:right;">
1.254
</td>
<td style="text-align:right;">
0.090
</td>
<td style="text-align:right;">
13.990
</td>
<td style="text-align:right;">
0
</td>
<td style="text-align:right;">
1.075
</td>
<td style="text-align:right;">
1.432
</td>
</tr>
</tbody>
</table>
<p>In Table <a href="8-nonlinear-variables.html#tab:quadextab">8.2</a>, note that there are two rows for Age–one for the linear or level term and a second for the quadratic term. When the quadratic relationship is an inverted U, or concave, the linear term will be positive and the quadratic will be negative. This corresponds with an initial positive relationship that eventually turns negative once the negative quadratic term overcomes the positive linear term.</p>
<p>Plugging our results from Table <a href="8-nonlinear-variables.html#tab:quadextab">8.2</a> into the regression equation, we obtain the following equation</p>
<p><span class="math display" id="eq:quadraticexsamp">\[\begin{equation}
\hat{Wage} = -22.7 + 1.4\times Age - 0.01\times Age^2 + 1.3\times Educ
\tag{8.6}
\end{equation}\]</span></p>
<p>We can answer questions regarding the predicted <em>value</em> of Wage the same way as before. For example, the predicted wage of an individual who is 40 years old with 16 years of education is</p>
<div class="sourceCode" id="cb15"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb15-1"><a href="8-nonlinear-variables.html#cb15-1"></a><span class="fl">-22.7</span> <span class="op">+</span><span class="st"> </span><span class="fl">1.4</span><span class="op">*</span><span class="dv">40</span> <span class="op">-</span><span class="st"> </span><span class="fl">0.01</span><span class="op">*</span><span class="dv">40</span><span class="op">^</span><span class="dv">2</span> <span class="op">+</span><span class="st"> </span><span class="fl">1.3</span><span class="op">*</span><span class="dv">16</span></span></code></pre></div>
<pre><code>## [1] 38.1</code></pre>
<p>dollars per hour.</p>
<p>To predict the <em>change</em> in wage given a change in age, we need to know the beginning point for age. For example, if we were asked what is the predicted change is wage for a 24-year old two years later who consequently increases their education from 16 to 18 to get their masters degree, we plug this scenario into Equation <a href="8-nonlinear-variables.html#eq:quadraticsampmarg">(8.3)</a> like so</p>
<div class="sourceCode" id="cb17"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb17-1"><a href="8-nonlinear-variables.html#cb17-1"></a><span class="dv">2</span><span class="op">*</span>(<span class="fl">1.4</span> <span class="op">-</span><span class="st"> </span><span class="dv">2</span><span class="op">*</span><span class="fl">0.01</span><span class="op">*</span><span class="dv">24</span>) <span class="op">+</span><span class="st"> </span><span class="fl">1.25</span><span class="op">*</span><span class="dv">2</span></span></code></pre></div>
<pre><code>## [1] 4.34</code></pre>
<p>providing us the answer of a predicted increase of $4.34.</p>
<p>Controlling for education, at what age do wages tend to reach their maximum? To answer, we plug the results into <a href="8-nonlinear-variables.html#eq:quadraticsampopt">(8.4)</a> like so</p>
<div class="sourceCode" id="cb19"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb19-1"><a href="8-nonlinear-variables.html#cb19-1"></a><span class="fl">-1.35</span><span class="op">/</span>(<span class="dv">2</span><span class="op">*-</span><span class="fl">0.013</span>)</span></code></pre></div>
<pre><code>## [1] 51.92308</code></pre>
<p>According to our results, wages reach their maximum at around 52 years of age.</p>
</div>
</div>
<div id="log-models" class="section level2">
<h2><span class="header-section-number">8.3</span> Log models</h2>
<p>Once again, we will forego the math of logarithms and instead focus on why we may want to use them in a regression model and how to interpret the results. In short, logarithms are used to express rates of change in a variable (i.e. percent change) rather than absolute change in a variable (i.e. unit change).</p>
<div id="logarithmic-scales" class="section level3">
<h3><span class="header-section-number">8.3.1</span> Logarithmic scales</h3>
<p>Graphs like Figure <a href="8-nonlinear-variables.html#fig:logcovid">8.2</a> below were commonplace during the initial COVID-19 spread. Take a look at the small note at the bottom explaining to readers the purpose of a logarithmic scale. Note how the values on the y axis are evenly dispersed, but each tick mark increases by a factor of 10 (i.e. the previous value multiplied by 10). The y-axis is in a <strong>log10</strong> scale. Another common log scale for visualization is a <strong>log2</strong> scale which increases each interval by a factor of 2.</p>
<p>The use of a log scale allows us to compare states like New York and Wyoming by taking into account large differences in absolute numbers. It would be unfair to compare the absolute number of COVID cases in New York to the absolute number of cases in Wyoming. It would also be unfair to compare the absolute number of new cases each day between the two states. A non-trivial portion of those numbers is a result of the size of the population in each state.</p>
<p>However, it is fair to compare the <em>rate</em> of growth between the two states. While it is obviously concerning that New York has over 300,000 deaths, the key feature of this graph is that we can compare the slopes of each state’s growth path because population size has been accounted for by the y-axis. Given New York’s population and population density, it was likely to have the most cases, but the state also had the fastest growth rate in cases from about day 5 to day 10.</p>
<div class="figure"><span id="fig:logcovid"></span>
<img src="images/logs_covid.png" alt="Growth in COVID-19 cases by state" width="508" />
<p class="caption">
Figure 8.2: Growth in COVID-19 cases by state
</p>
</div>
</div>
<div id="percent-v-percentage-point-change" class="section level3">
<h3><span class="header-section-number">8.3.2</span> Percent v percentage point change</h3>
<p>Rate of change typically refers to percent change. The equation for percent change is shown below.</p>
<p><span class="math display" id="eq:pctchange">\[\begin{equation}
PctChange = {\frac{NewValue-OldValue}{OldValue}} \times 100
\tag{8.7}
\end{equation}\]</span></p>
<p>For example, if the number of COVID cases increase from 1,000 to 10,000 over the course of a week, the absolute change is 9,000. The percent change is 900%.</p>
<p>A common cause of confusion is the difference between a percent change and a percentage point change. This occurs when we discuss the change in a variable that is already expressed as a percent. For example, if the U.S. unemployment rate increases from 4% to 15% during the pandemic, that’s an absolute change of 11 percentage points. The unemployment rate is expressed units of percentage points, so a unit change is a percentage point change. An increase from 4% to 15% is also a 275% percent change.</p>
<p>As we have seen in previous examples of regression, when we include a variable that is not log-transformed, regression estimates the <strong>unit change</strong> in <span class="math inline">\(y\)</span> given a <strong>unit change</strong> in <span class="math inline">\(x\)</span>. If a variable is expressed in units of percentages like unemployment or poverty, then a unit change for those variables is a percentage point change. Including a log-transformed variable in regression estimates percent changes in the variable(s) we transformed.</p>
<p>One reason we may prefer to use percent change is if the variable in question has some underlying impact that differs depending on the initial value from which it changed. This too applies to measures of wealth or income. Suppose we estimate that a policy will, on average, increase peoples’ incomes by 12,000 dollars. This average unit change does not quite capture the benefit of the policy. Imagine a society of two people. One person earns 20,000 dollars per year and the other earns 80,000 dollars. That 12,000 likely has a greater positive impact on the low-income individual than it does the high-income individual. Consequently, this can be expressed in percent change. The 12,000 represents a 60% increase in income for the low-income individual and 15% for the high-income individual.</p>
</div>
<div id="why-logs-in-regression" class="section level3">
<h3><span class="header-section-number">8.3.3</span> Why logs in regression</h3>
<p>To summarize, we may want to use logs in regression if</p>
<ul>
<li>it is preferable to express change in percentages rather than units</li>
<li>a variable we intend to include has a skewed distribution</li>
<li>we theorize the relationship between two variables follows a logarithmic path</li>
</ul>
<p>Let’s consider these last two reasons further. As was mentioned, log scales allow us to compare numbers that are very far apart, as seen in Figure <a href="8-nonlinear-variables.html#fig:logcovid">8.2</a>. If the scale for COVID cases were left in constant units, New York and a few other states would be so far above most other states that it would be difficult to fit in a sensible graph. Using logs condensed or pulled those extreme numbers back to a more compact distribution.</p>
<p>As will become clear in the next section on inference, using a sample to make valid conclusions about a population relies heavily on the normal distribution, which was introduced in Chapter <a href="4-descriptive-statistics.html#descriptive-statistics">4</a>. In a similar sense, we want the variables we use for inference to be approximately normally distributed because extreme values of a skewed distribution can impose undue influence on our results. Log-transformations can transform a skewed distribution to be more normal.</p>
<p>For instance, variables that measure income or wealth tend to be right-skewed. Figure <a href="8-nonlinear-variables.html#fig:gapskew">8.3</a> shows the distribution of GDP per capita across most countries in multiple years. Clearly this distribution is not normal and skewed to the right. It is difficult to see because there are so few cases, but some countries have GDP per capita near or more than $120,000.</p>
<p>Figure <a href="8-nonlinear-variables.html#fig:gaplog">8.4</a> shows the distribution if we convert GDP per capita to a log scale (log10 was used but any log scale will achieve the same normalization). Now we have a more normal distribution. This is desirable in statistics.</p>
<div class="figure"><span id="fig:gapskew"></span>
<img src="data-apps-text_files/figure-html/gapskew-1.png" alt="Distribution of GDP per capita" width="672" />
<p class="caption">
Figure 8.3: Distribution of GDP per capita
</p>
</div>
<div class="figure"><span id="fig:gaplog"></span>
<img src="data-apps-text_files/figure-html/gaplog-1.png" alt="Distribution of log10 GDP per capita" width="672" />
<p class="caption">
Figure 8.4: Distribution of log10 GDP per capita
</p>
</div>
<p>The third reason for using logs concerns theory, which should always inform the choices we make in statistics. When choosing how to model the relationship between an outcome and an explanatory variable, if past research, experience, visualization of data, or intuition tells us that the outcome changes dramatically at first, then begins to flatten, a logarithmic transformation should be used.</p>
<p>For example, suppose we wish to examine the relationship between national wealth and life expectancy. Intuitively, we expect this relationship to be positive–as wealth increases, life expectancy should increase. Also, life expectancy has some natural ceiling, so it cannot increase indefinitely, and we may expect relatively small increases from low levels of wealth to have much greater impacts on life expectancy then similar increases from high levels of wealth.</p>
<p>Figure <a href="8-nonlinear-variables.html#fig:gapskewscatter">8.5</a> provides a scatter plot of GDP per capita and life expectancy in their original units. Note the rapid increase then plateau in life expectancy. A regression line would not fit these data well.</p>
<div class="figure"><span id="fig:gapskewscatter"></span>
<img src="data-apps-text_files/figure-html/gapskewscatter-1.png" alt="Relationship between wealth and life expectancy using unit scale" width="672" />
<p class="caption">
Figure 8.5: Relationship between wealth and life expectancy using unit scale
</p>
</div>
<p>Using a log transformation in an association between two variables does not change the underlying data or relationship, but it <em>does</em> transform the pattern of points to be more linear, thus allowing a linear regression line to do a better job modeling the relationship. Figure <a href="8-nonlinear-variables.html#fig:gaplogscatter">8.6</a> uses the same data but GDP per capita has been transformed to log scale. This simple change makes a big difference for the validity of any conclusions we may make regarding the relationship between wealth and life expectancy.</p>
<div class="figure"><span id="fig:gaplogscatter"></span>
<img src="data-apps-text_files/figure-html/gaplogscatter-1.png" alt="Relationship between wealth and life expectancy using log scale" width="672" />
<p class="caption">
Figure 8.6: Relationship between wealth and life expectancy using log scale
</p>
</div>
</div>
<div id="using-log-models" class="section level3">
<h3><span class="header-section-number">8.3.4</span> Using log models</h3>
<p>There are three variations of the log model:</p>
<ul>
<li>Level-log: log transforming one or more explanatory variables but not the outcome</li>
<li>Log-level: log transforming the outcome but not an explanatory variable</li>
<li>Log-log: log transforming the outcome and an explanatory variable</li>
</ul>
<p>Each model fits slightly different patterns of association best but they share the general pattern of a pronounced initial increase or decrease followed by a plateau. If past research, visuals, or theory does not lead us to choose one model over the other, one option is to compare the goodness-of-fit between the three, choosing the one with the highest <span class="math inline">\(R^2\)</span> or lowest RMSE.</p>
<p>One last point before presenting each of the models and how to interpret: using the logarithmic transformation uses a special log scale called the <strong>natural log</strong>, often denoted as <strong><span class="math inline">\(ln\)</span></strong>, as opposed to, say, <span class="math inline">\(log_{10}\)</span> or <span class="math inline">\(log_2\)</span>. You do not need to concern yourself with the mathematical properties of the natural log. Just know that the natural log is what is used in regression to transform unit changes to percent changes.</p>
<div id="log-log" class="section level4 unnumbered">
<h4>Log-log</h4>
<p>The log-log model is somewhat special among the three variations because it estimates a commonly used measure in economic or policy analyses–the <strong>elasticity</strong>. You may have already learned in policy analysis courses that the <strong>elasticity is the percent change in an outcome given a one percent change in the explanatory variable</strong>.</p>
<p>Equation <a href="8-nonlinear-variables.html#eq:loglog">(8.8)</a> presents a generic log-log model. Log-log is simply meant to convey that we logged our outcome and logged at least one explanatory variable.</p>
<p><span class="math display" id="eq:loglog">\[\begin{equation}
ln(y)=\beta_0 + \beta_1ln(x_1) + \beta_2x_2 + \cdots + \beta_kx_k + \epsilon
\tag{8.8}
\end{equation}\]</span></p>
<p>Thus, the sample equation is</p>
<p><span class="math display" id="eq:loglogsamp">\[\begin{equation}
\hat{ln(y)}=b_0 + b_1ln(x_1) + b_2x_2 + \cdots + b_kx_k
\tag{8.9}
\end{equation}\]</span></p>
<p>When we obtain an estimate for <span class="math inline">\(b_1\)</span> we can plug it into the following template</p>
<blockquote>
<p>On average, a one percent change in <span class="math inline">\(x_1\)</span> is associated with a <span class="math inline">\(b_1\)</span> percent change in <span class="math inline">\(y\)</span>, all else equal.</p>
</blockquote>
<p>Or, if we wanted to report using elasticity language, assuming our audience understands what we are talking about:</p>
<blockquote>
<p>According to the results, the <span class="math inline">\(x_1\)</span> elasiticy of <span class="math inline">\(y\)</span> is <span class="math inline">\(b_1\)</span>.</p>
</blockquote>
</div>
<div id="level-log" class="section level4 unnumbered">
<h4>Level-log</h4>
<p>Equation <a href="8-nonlinear-variables.html#eq:levlog">(8.10)</a> presents a generic level-log model. Level-log is simply meant to convey that we logged at least one explanatory variable.</p>
<p><span class="math display" id="eq:levlog">\[\begin{equation}
y=\beta_0 + \beta_1ln(x_1) + \beta_2x_2 + \cdots + \beta_kx_k + \epsilon
\tag{8.10}
\end{equation}\]</span></p>
<p>Thus, the sample equation is</p>
<p><span class="math display" id="eq:levlogsamp">\[\begin{equation}
\hat{y}=b_0 + b_1ln(x_1) + b_2x_2 + \cdots + b_kx_k
\tag{8.11}
\end{equation}\]</span></p>
<p>When we obtain an estimate for <span class="math inline">\(b_1\)</span> we can plug it into the following template</p>
<blockquote>
<p>On average, a one percent change in <span class="math inline">\(x_1\)</span> is associated with a <span class="math inline">\(\frac{b_1}{100}\)</span> unit change in <span class="math inline">\(y\)</span>, all else equal.</p>
</blockquote>
<p>Or, if dividing our estimate by 100 results in too small of a number to report, we can say the following</p>
<blockquote>
<p>On average, a doubling of <span class="math inline">\(x_1\)</span> is associated with a <span class="math inline">\(b_1\)</span> unit change in <span class="math inline">\(y\)</span>, all else equal.</p>
</blockquote>
<p>because a doubling is equal to a 100 percent increase. Multiplying <span class="math inline">\(\frac{b_1}{100}\)</span> by 100 cancels out the 100 in the denominator, leaving us with just <span class="math inline">\(b_1\)</span>.</p>
</div>
<div id="log-level" class="section level4 unnumbered">
<h4>Log-level</h4>
<p>Equation <a href="8-nonlinear-variables.html#eq:loglev">(8.12)</a> presents a generic log-level model. Log-level is simply meant to convey that we logged our outcome.</p>
<p><span class="math display" id="eq:loglev">\[\begin{equation}
ln(y)=\beta_0 + \beta_1x_1 + \beta_2x_2 + \cdots + \beta_kx_k + \epsilon
\tag{8.12}
\end{equation}\]</span></p>
<p>Thus, the sample equation is</p>
<p><span class="math display" id="eq:loglevsamp">\[\begin{equation}
\hat{ln(y)}=b_0 + b_1x_1 + b_2x_2 + \cdots + b_kx_k
\tag{8.13}
\end{equation}\]</span></p>
<p>When we obtain an estimate for <span class="math inline">\(b_1\)</span> we can plug it into the following template</p>
<blockquote>
<p>On average, a one unit change in <span class="math inline">\(x_1\)</span> is associated with a <span class="math inline">\(b_1 \times 100\)</span> percent change in <span class="math inline">\(y\)</span>, all else equal.</p>
</blockquote>
</div>
<div id="example" class="section level4 unnumbered">
<h4>Example</h4>
<p>Let’s continue our investigation of national life expectancy using the various log models. Suppose we are interested in using the following base model for the three varieties of log models. Continent is included because perhaps we think it will capture some geographical, social, and/or cultural differences that impact life expectancy.</p>
<p><span class="math display" id="eq:logex">\[\begin{equation}
LifeExp=\beta_0 + \beta_1GDPpercap + \beta_2Continent + \epsilon
\tag{8.14}
\end{equation}\]</span></p>
<p>The following tables present results for each of the three log models.</p>
<table>
<caption>
<span id="tab:loglogtab">Table 8.3: </span>Log-log results
</caption>
<thead>
<tr>
<th style="text-align:left;">
term
</th>
<th style="text-align:right;">
estimate
</th>
<th style="text-align:right;">
std_error
</th>
<th style="text-align:right;">
statistic
</th>
<th style="text-align:right;">
p_value
</th>
<th style="text-align:right;">
lower_ci
</th>
<th style="text-align:right;">
upper_ci
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;">
intercept
</td>
<td style="text-align:right;">
3.062
</td>
<td style="text-align:right;">
0.026
</td>
<td style="text-align:right;">
117.692
</td>
<td style="text-align:right;">
0
</td>
<td style="text-align:right;">
3.011
</td>
<td style="text-align:right;">
3.113
</td>
</tr>
<tr>
<td style="text-align:left;">
log(gdpPercap)
</td>
<td style="text-align:right;">
0.112
</td>
<td style="text-align:right;">
0.004
</td>
<td style="text-align:right;">
31.843
</td>
<td style="text-align:right;">
0
</td>
<td style="text-align:right;">
0.105
</td>
<td style="text-align:right;">
0.119
</td>
</tr>
<tr>
<td style="text-align:left;">
continentAmericas
</td>
<td style="text-align:right;">
0.133
</td>
<td style="text-align:right;">
0.011
</td>
<td style="text-align:right;">
12.519
</td>
<td style="text-align:right;">
0
</td>
<td style="text-align:right;">
0.112
</td>
<td style="text-align:right;">
0.154
</td>
</tr>
<tr>
<td style="text-align:left;">
continentAsia
</td>
<td style="text-align:right;">
0.110
</td>
<td style="text-align:right;">
0.009
</td>
<td style="text-align:right;">
12.037
</td>
<td style="text-align:right;">
0
</td>
<td style="text-align:right;">
0.092
</td>
<td style="text-align:right;">
0.128
</td>
</tr>
<tr>
<td style="text-align:left;">
continentEurope
</td>
<td style="text-align:right;">
0.166
</td>
<td style="text-align:right;">
0.012
</td>
<td style="text-align:right;">
14.357
</td>
<td style="text-align:right;">
0
</td>
<td style="text-align:right;">
0.143
</td>
<td style="text-align:right;">
0.189
</td>
</tr>
<tr>
<td style="text-align:left;">
continentOceania
</td>
<td style="text-align:right;">
0.152
</td>
<td style="text-align:right;">
0.029
</td>
<td style="text-align:right;">
5.187
</td>
<td style="text-align:right;">
0
</td>
<td style="text-align:right;">
0.095
</td>
<td style="text-align:right;">
0.210
</td>
</tr>
</tbody>
</table>
<table>
<caption>
<span id="tab:levlogtab">Table 8.4: </span>Level-log results
</caption>
<thead>
<tr>
<th style="text-align:left;">
term
</th>
<th style="text-align:right;">
estimate
</th>
<th style="text-align:right;">
std_error
</th>
<th style="text-align:right;">
statistic
</th>
<th style="text-align:right;">
p_value
</th>
<th style="text-align:right;">
lower_ci
</th>
<th style="text-align:right;">
upper_ci
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;">
intercept
</td>
<td style="text-align:right;">
2.317
</td>
<td style="text-align:right;">
1.359
</td>
<td style="text-align:right;">
1.704
</td>
<td style="text-align:right;">
0.088
</td>
<td style="text-align:right;">
-0.349
</td>
<td style="text-align:right;">
4.983
</td>
</tr>
<tr>
<td style="text-align:left;">
log(gdpPercap)
</td>
<td style="text-align:right;">
6.422
</td>
<td style="text-align:right;">
0.183
</td>
<td style="text-align:right;">
35.003
</td>
<td style="text-align:right;">
0.000
</td>
<td style="text-align:right;">
6.062
</td>
<td style="text-align:right;">
6.782
</td>
</tr>
<tr>
<td style="text-align:left;">
continentAmericas
</td>
<td style="text-align:right;">
7.015
</td>
<td style="text-align:right;">
0.554
</td>
<td style="text-align:right;">
12.652
</td>
<td style="text-align:right;">
0.000
</td>
<td style="text-align:right;">
5.927
</td>
<td style="text-align:right;">
8.102
</td>
</tr>
<tr>
<td style="text-align:left;">
continentAsia
</td>
<td style="text-align:right;">
5.912
</td>
<td style="text-align:right;">
0.477
</td>
<td style="text-align:right;">
12.400
</td>
<td style="text-align:right;">
0.000
</td>
<td style="text-align:right;">
4.977
</td>
<td style="text-align:right;">
6.847
</td>
</tr>
<tr>
<td style="text-align:left;">
continentEurope
</td>
<td style="text-align:right;">
9.577
</td>
<td style="text-align:right;">
0.604
</td>
<td style="text-align:right;">
15.855
</td>
<td style="text-align:right;">
0.000
</td>
<td style="text-align:right;">
8.392
</td>
<td style="text-align:right;">
10.762
</td>
</tr>
<tr>
<td style="text-align:left;">
continentOceania
</td>
<td style="text-align:right;">
9.213
</td>
<td style="text-align:right;">
1.536
</td>
<td style="text-align:right;">
5.999
</td>
<td style="text-align:right;">
0.000
</td>
<td style="text-align:right;">
6.201
</td>
<td style="text-align:right;">
12.226
</td>
</tr>
</tbody>
</table>
<table>
<caption>
<span id="tab:loglevtab">Table 8.5: </span>Log-level results
</caption>
<thead>
<tr>
<th style="text-align:left;">
term
</th>
<th style="text-align:right;">
estimate
</th>
<th style="text-align:right;">
std_error
</th>
<th style="text-align:right;">
statistic
</th>
<th style="text-align:right;">
p_value
</th>
<th style="text-align:right;">
lower_ci
</th>
<th style="text-align:right;">
upper_ci
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;">
intercept
</td>
<td style="text-align:right;">
3.856
</td>
<td style="text-align:right;">
0.006
</td>
<td style="text-align:right;">
601.881
</td>
<td style="text-align:right;">
0
</td>
<td style="text-align:right;">
3.843
</td>
<td style="text-align:right;">
3.869
</td>
</tr>
<tr>
<td style="text-align:left;">
gdpPercap
</td>
<td style="text-align:right;">
0.000
</td>
<td style="text-align:right;">
0.000
</td>
<td style="text-align:right;">
16.374
</td>
<td style="text-align:right;">
0
</td>
<td style="text-align:right;">
0.000
</td>
<td style="text-align:right;">
0.000
</td>
</tr>
<tr>
<td style="text-align:left;">
continentAmericas
</td>
<td style="text-align:right;">
0.250
</td>
<td style="text-align:right;">
0.011
</td>
<td style="text-align:right;">
22.054
</td>
<td style="text-align:right;">
0
</td>
<td style="text-align:right;">
0.228
</td>
<td style="text-align:right;">
0.272
</td>
</tr>
<tr>
<td style="text-align:left;">
continentAsia
</td>
<td style="text-align:right;">
0.160
</td>
<td style="text-align:right;">
0.010
</td>
<td style="text-align:right;">
15.322
</td>
<td style="text-align:right;">
0
</td>
<td style="text-align:right;">
0.140
</td>
<td style="text-align:right;">
0.181
</td>
</tr>
<tr>
<td style="text-align:left;">
continentEurope
</td>
<td style="text-align:right;">
0.311
</td>
<td style="text-align:right;">
0.012
</td>
<td style="text-align:right;">
26.383
</td>
<td style="text-align:right;">
0
</td>
<td style="text-align:right;">
0.288
</td>
<td style="text-align:right;">
0.334
</td>
</tr>
<tr>
<td style="text-align:left;">
continentOceania
</td>
<td style="text-align:right;">
0.316
</td>
<td style="text-align:right;">
0.034
</td>
<td style="text-align:right;">
9.381
</td>
<td style="text-align:right;">
0
</td>
<td style="text-align:right;">
0.250
</td>
<td style="text-align:right;">
0.382
</td>
</tr>
</tbody>
</table>
<p>Our log-log results indicate that a one percent increase in GDP per capita is associated with a 0.11 percent increase in life expectancy, on average and controlling for continent.</p>
<p>Our level-log results indicate that a one percent increase in GDP per capita is associated with an increase in life expectancy of 0.06 years.</p>
<p>Our log-level results indicate that a one dollar increase in GDP per capita is associated with a indiscernible percent increase in life expectancy. Changing GDP per capita from dollars to something like thousands of dollars would probably give an estimate that doesn’t round to 0.</p>
<p>The continent estimates can be interpreted in similar fashion, remembering that with categorical variables, the estimate of each level of the variable is relative to the base comparison excluded from the equation. In this example, Africa is the base comparison. Let’s focus on Asia for interpretation.</p>
<p>Our log-log results indicate that life expectancy in Asia is 110% greater than life expectancy in Africa. Since a dummy variable can only change from 0 to 1, this is equivalent to a 100 percent change. Therefore, we must multiply our estimate by 100.</p>
<p>Our level-log results indicate that life expectancy in Asia is 5.9 years greater than life expectancy in Africa. Lastly, our log-level results indicate that life expectancy in Asia is 160% greater than life expectancy in Africa.</p>
<p><br></p>
<blockquote>
<p><strong>To learn how to include nonlinear variables in regression using R, proceed to Chapter <a href="23-r-nonlinear-regression.html#r-nonlinear-regression">23</a>.</strong></p>
</blockquote>
</div>
</div>
</div>
<div id="kt8" class="section level2">
<h2><span class="header-section-number">8.4</span> Key terms and concepts</h2>
<div class="learncheck">
<ul>
<li>
Marginal effect
</li>
<li>
Logarithmic scale
</li>
<li>
Percent change
</li>
<li>
Percentage point change
</li>
<li>
Natural log
</li>
<li>
Elasticity
</li>
</ul>
</div>

</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="7-categorical-variables-and-interactions.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="9-causation-and-bias.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/lunr.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": false,
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": null,
"text": null
},
"history": {
"link": null,
"text": null
},
"view": {
"link": null,
"text": null
},
"download": null,
"toc": {
"collapse": "section"
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
